import {notFound} from 'next/navigation';
import Link from '@/components/navigation/ContextLink';
import {requireAdminContext} from '@/lib/auth';
import {loadAdminClientProfile} from '@/lib/admin-config/client-profile-data';
import {adminPanel,AdminReadError} from '../../_components/AdminReadUi';
const record=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const amount=(v:unknown)=>v===null||v===undefined?'—':Number.isFinite(Number(v))?new Intl.NumberFormat('es-VE',{style:'currency',currency:'USD'}).format(Number(v)):'—';
export default async function ClientProfile({params,searchParams}:{params:Promise<{clientId:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 await requireAdminContext();const id=Number((await params).clientId),query=await searchParams;
 let data;try{data=await loadAdminClientProfile(id,query.consultar==='1');}catch{return <AdminReadError title="Cliente" message="No se pudo consultar la ficha. No se modificaron sus datos."/>;}
 if(!data)notFound();
 const {client,commercial}=data,metrics=record(commercial?.metrics);
 const recent=Array.isArray(commercial?.recent_activity)?commercial.recent_activity.map(record):[],pending=Array.isArray(commercial?.pending_orders)?commercial.pending_orders.map(record):[];
 return <div className="max-w-4xl space-y-3"><header className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="text-lg font-semibold text-[#DEDEE6]">{client.full_name}</h1><p className="text-xs text-[#9B9BA7]">{client.phone} · {client.is_active?'Activo':'Inactivo'}</p></div><Link href={'/app/admin/configuracion/clientes?id='+id} prefetch={false} className="inline-flex min-h-11 items-center text-xs text-[#FFFF00]">Editar cliente →</Link></header>
 <section className={adminPanel}><dl className="grid grid-cols-2 gap-3"><div><dt className="text-[11px] text-[#9B9BA7]">Saldo a favor</dt><dd className="text-lg tabular-nums">{amount(client.fund_balance_usd)}</dd></div><div><dt className="text-[11px] text-[#9B9BA7]">Tipo</dt><dd className="text-sm">{client.client_type==='own'?'Propio':client.client_type==='assigned'?'Asignado':client.client_type||'Sin clasificar'}</dd></div></dl></section>
 <nav className="flex flex-wrap gap-2"><Link href={'/app/admin/clientes/'+id+'?consultar=1'} prefetch={false} className="inline-flex min-h-11 items-center rounded-lg bg-[#FFFF00] px-3 text-xs font-semibold text-black">{commercial?'Actualizar ficha comercial':'Consultar ficha comercial'}</Link><Link href={'/app/admin/finanzas/cobranzas?q='+encodeURIComponent(client.full_name||'')} prefetch={false} className="inline-flex min-h-11 items-center px-3 text-xs underline">Cobranza por período →</Link></nav>
 {commercial?<><section className={adminPanel}><dl className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Compras',metrics.purchase_count],['Venta neta',amount(metrics.net_revenue_usd)],['Ticket promedio',amount(metrics.average_ticket_usd)],['Última compra',metrics.last_purchase_on||'—'],['Primera compra',metrics.first_purchase_on||'—'],['Días sin comprar',metrics.days_since_last_purchase??'—'],['Ritmo (días)',metrics.cadence_days??'—'],['Último asesor',metrics.last_advisor_name||'—']].map(([label,value])=><div key={String(label)}><dt className="text-[11px] text-[#9B9BA7]">{String(label)}</dt><dd className="mt-1 text-sm tabular-nums">{String(value??'—')}</dd></div>)}</dl></section>
 <section className={adminPanel}><h2 className="text-sm font-medium">Pedidos en curso · {String(commercial.pending_order_count??pending.length)}</h2>{pending.map(o=><Link key={String(o.id)} href={'/app/admin/ordenes?openOrder='+Number(o.id)} prefetch={false} className="mt-2 flex min-h-11 items-center justify-between gap-2 border-b border-[#292937] py-2 text-xs"><span className="text-[#FFFF00]">#{Number(o.id)}</span><span>{String(o.scheduled_date||o.created_at||'').slice(0,10)}</span><span>{amount(o.total_usd)}</span></Link>)}</section>
 <details className={adminPanel}><summary className="min-h-11 cursor-pointer content-center text-sm">Actividad reciente · últimas 10</summary>{recent.map((r,i)=><div key={i} className="flex min-h-11 flex-wrap items-center justify-between gap-2 border-t border-[#292937] py-2 text-xs"><span>{String(r.purchased_at||'').slice(0,10)} · {r.event_kind==='gift_only'?'Obsequio':'Compra'} · {r.origin==='live'?'Actual':'Importada'}</span><span>{String(r.advisor_name||'—')} · {amount(r.net_total_usd)}</span></div>)}</details></>:<p className="text-xs text-[#9B9BA7]">Las compras, pedidos y métricas comerciales se consultan cuando lo solicites.</p>}
 </div>;
}
