-- Historical proposal; superseded after explicit authorization on 2026-10-03.
-- Canonical implementation and tests:
-- supabase/migrations/20261003171627_admin_configuration_atomic.sql
-- This file intentionally contains no executable SQL or second implementation.
