import Link from '@/components/navigation/ContextLink';
import WorkspaceForm from '@/components/navigation/WorkspaceForm';
import {requireAdminContext} from '@/lib/auth';
import {analysisFilters,summarizeAnalysis,type AnalysisFilters} from '@/lib/admin-finance/commercial-analysis-model';
import {loadCommercialAnalysis} from '@/lib/admin-finance/commercial-analysis-data';
import {AdminReadError,adminPanel} from '../_components/AdminReadUi';
import {getCaracasDateKey} from '@/lib/admin-finance/period';
const input='min-h-11 min-w-0 rounded-lg border border-[#30303D] bg-[#14141C] px-2 text-xs';
const usd=(n:number)=>new Intl.NumberFormat('es-VE',{style:'currency',currency:'USD'}).format(n);
export default async function AnalysisPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 await requireAdminContext();const params=await searchParams;let filters:AnalysisFilters,data;
 try{filters=analysisFilters(params);data=await loadCommercialAnalysis(filters,params.consultar==='1');}
 catch(error){return <AdminReadError title="Análisis comercial" message={error instanceof Error?error.message:'No se pudo verificar el período.'}/>;}
 const today=getCaracasDateKey(new Date());
 const href=(patch:Partial<AnalysisFilters>)=>'/app/admin/analisis?'+new URLSearchParams({...Object.fromEntries(Object.entries({...filters,...patch}).map(([key,value])=>[key,String(value)])),consultar:'1'});
 const groups=new Map<string,NonNullable<typeof data>['rows']>();
 const exportHref='/app/admin/analisis/exportar?'+new URLSearchParams(Object.fromEntries(Object.entries(filters).map(([key,value])=>[key,String(value)])));
 if(data)for(const row of data.rows){const group=groups.get(row.personId)??[];group.push(row);groups.set(row.personId,group);}
 return <div className="space-y-3"><header className="flex flex-wrap items-center justify-between gap-2"><h1 className="text-lg font-semibold text-[#DEDEE6]">Análisis comercial</h1><Link href="/app/admin/proyecciones" prefetch={false} className="inline-flex min-h-11 items-center text-xs text-[#FFFF00]">Proyecciones →</Link></header>
 <WorkspaceForm action="/app/admin/analisis" method="get" className={adminPanel+' grid gap-2 sm:grid-cols-3 xl:grid-cols-6'}><input type="hidden" name="consultar" value="1"/><input type="hidden" name="details" value="none"/>
 <label className="grid gap-1 text-xs">Desde<input type="date" name="from" defaultValue={filters.from||today} required className={input}/></label><label className="grid gap-1 text-xs">Hasta<input type="date" name="to" defaultValue={filters.to||today} required className={input}/></label>
 <label className="grid gap-1 text-xs">Fecha<select name="basis" defaultValue={filters.basis} className={input}><option value="scheduled">Programada</option><option value="created">Creación</option></select></label>
 <label className="grid gap-1 text-xs">Canal<select name="source" defaultValue={filters.source} className={input}><option value="all">Todos</option><option value="advisor">Asesores</option><option value="master">Master / Admin</option><option value="walk_in">Mostrador</option></select></label>
 <label className="grid gap-1 text-xs">Entrega<select name="fulfillment" defaultValue={filters.fulfillment} className={input}><option value="all">Todas</option><option value="pickup">Pickup</option><option value="delivery">Delivery</option></select></label>
 <button className="min-h-11 self-end rounded-lg bg-[#FFFF00] px-3 text-xs font-semibold text-black">Consultar</button>
 <label className="grid gap-1 text-xs sm:col-span-2">Vendedor<select name="person" defaultValue={filters.person} className={input}><option value="">Todos</option>{(data?.people??[]).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}{filters.person&&!data?.people.some(p=>p.id===filters.person)?<option value={filters.person}>Vendedor seleccionado</option>:null}</select></label>
 <label className="grid gap-1 text-xs">Responsabilidad<select name="personBasis" defaultValue={filters.personBasis} className={input}><option value="either">Creador o asesor</option><option value="creator">Creador de la orden</option><option value="advisor">Asesor atribuido</option></select></label>
 </WorkspaceForm>
 {data?<><section className={adminPanel}><dl className="grid grid-cols-2 gap-3 sm:grid-cols-5">{[['Fact. neta',usd(data.totals.netUsd)],['Cierres',data.totals.closures],['Promedio',usd(data.totals.averageUsd)],['Abonado',usd(data.totals.paidUsd)],['Pendiente',usd(data.totals.pendingUsd)]].map(([label,value])=><div key={label}><dt className="text-[11px] text-[#9B9BA7]">{label}</dt><dd className="mt-1 text-lg font-semibold tabular-nums text-[#DEDEE6]">{value}</dd></div>)}</dl><p className="mt-2 text-[11px] text-[#9B9BA7]">Órdenes entregadas. Facturación neta sin impuesto; abonado y pendiente incluyen el total de la orden y son saldos actuales.</p></section>
 <nav className="flex flex-wrap gap-2 text-xs"><a href={exportHref} className="inline-flex min-h-11 items-center rounded-lg border border-[#30303D] px-3 text-[#FFFF00]">Descargar CSV del filtro</a>{[['Pagos puntuales / tardíos','payments'],['Clientes nuevos','clients'],['Estimar comisiones','commissions']].map(([label,details])=><Link key={details} href={href({details:details as AnalysisFilters['details'],page:1})} prefetch={false} className="inline-flex min-h-11 items-center rounded-lg border border-[#30303D] px-3 text-[#FFFF00]">{label}</Link>)}</nav>
 {data.collection?<section className={adminPanel}><h2 className="mb-2 text-sm font-medium">Fecha de registro del pago</h2><dl className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Puntuales',data.collection.orders.filter(o=>o.status==='punctual_paid').length],['Tardíos',data.collection.orders.filter(o=>o.status==='credit_paid'||o.status==='overdue_paid').length],['Con deuda',data.collection.orders.filter(o=>o.pendingUsd>=0.01).length],['Sin fecha verificable',data.collection.orders.filter(o=>o.status==='missing_registration').length]].map(([label,value])=><div key={label}><dt className="text-[11px] text-[#9B9BA7]">{label}</dt><dd className="text-base tabular-nums">{value}</dd></div>)}</dl></section>:null}
 {data.newClients?<section className={adminPanel}><h2 className="mb-2 text-sm font-medium">Primera compra · clientes nuevos</h2><dl className="grid grid-cols-3 gap-3">{[['Propios',data.newClients.own],['Asignados',data.newClients.assigned],['Otros',data.newClients.other]].map(([label,value])=><div key={label}><dt className="text-[11px] text-[#9B9BA7]">{label}</dt><dd className="text-base">{value}</dd></div>)}</dl><p className="mt-2 text-[11px] text-[#9B9BA7]">Conserva el corte de importación del 2 de junio; no vuelve a contar compras posteriores.</p></section>:null}
 {data.commissionUsd!==null?<section className={adminPanel}><h2 className="text-sm font-medium">Comisión estimada · {usd(data.commissionUsd)}</h2><WorkspaceForm action="/app/admin/analisis" method="get" className="mt-2 flex flex-wrap items-end gap-2">{Object.entries({...filters,details:'commissions',consultar:'1'}).filter(([key])=>key!=='basePct').map(([key,value])=><input type="hidden" key={key} name={key} value={String(value)}/>)}<label className="grid gap-1 text-xs">Porcentaje general<input type="number" min="0" max="100" step="0.01" name="basePct" defaultValue={filters.basePct} required className={input}/></label><button className="min-h-11 rounded-lg border border-[#30303D] px-3 text-xs">Recalcular</button></WorkspaceForm><p className="mt-2 text-[11px] text-[#9B9BA7]">Incluye reglas fechadas de productos y ajustes de comisión. Es una estimación, no un cierre ni un pago.</p><Link href="/app/admin/finanzas/comisiones" prefetch={false} className="inline-flex min-h-11 items-center text-xs text-[#FFFF00]">Abrir liquidaciones →</Link></section>:null}
 <details className={adminPanel}><summary className="min-h-11 cursor-pointer content-center text-sm">Resultados por vendedor · {groups.size}</summary><div className="divide-y divide-[#292937]">{Array.from(groups,([id,rows])=>{const t=summarizeAnalysis(rows);return <div key={id} className="flex flex-wrap items-center justify-between gap-2 py-2 text-xs"><Link href={href({person:id==='unknown'?'':id,page:1})} prefetch={false} className="inline-flex min-h-11 items-center underline">{rows[0].personName}</Link><span>{t.closures} cierres · {usd(t.netUsd)} · Pendiente {usd(t.pendingUsd)}</span></div>})}</div></details>
 <section className={adminPanel}><h2 className="mb-2 text-sm font-medium">Órdenes · {data.rows.length}</h2><div className="divide-y divide-[#292937]">{data.rows.slice((filters.page-1)*30,filters.page*30).map(r=><Link key={r.id} href={'/app/admin/ordenes?openOrder='+r.id+'&focusDate='+r.date} prefetch={false} className="grid min-h-11 grid-cols-[65px_minmax(0,1fr)_auto] items-center gap-2 py-2 text-xs"><span className="text-[#FFFF00]">#{r.id}</span><span className="min-w-0"><span className="block truncate">{r.client}</span><span className="text-[11px] text-[#9B9BA7]">{r.date} · {r.personName}</span></span><span className="text-right tabular-nums"><span className="block">{usd(r.netUsd)}</span><span className="text-[11px] text-[#9B9BA7]">Pend. {usd(r.pendingUsd)}</span></span></Link>)}</div><nav className="mt-2 flex justify-between gap-2 text-xs">{filters.page>1?<Link href={href({page:filters.page-1})} prefetch={false} className="inline-flex min-h-11 items-center underline">Anterior</Link>:<span/>}<span className="content-center">Página {filters.page} de {Math.max(1,Math.ceil(data.rows.length/30))}</span>{filters.page*30<data.rows.length?<Link href={href({page:filters.page+1})} prefetch={false} className="inline-flex min-h-11 items-center underline">Siguiente</Link>:<span/>}</nav></section>
 </>:<p className="text-xs text-[#9B9BA7]">Selecciona el período y consulta. Los desgloses se cargan solo al solicitarlos.</p>}
 </div>;
}
