import Link from '@/components/navigation/ContextLink';
import WorkspaceForm from '@/components/navigation/WorkspaceForm';
import {requireAdminContext} from '@/lib/auth';
import {loadAdminAdjustmentAudit} from '@/lib/admin-config/audit-data';
import {getCaracasDateKey} from '@/lib/admin-finance/period';
import {AdminReadError,adminPanel} from '../../_components/AdminReadUi';
const input='min-h-11 min-w-0 rounded-lg border border-[#30303D] bg-[#14141C] px-2 text-xs';
const record=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const titles:Record<string,string>={account:'Cuenta',rules:'Permisos de pago',baseline:'Saldo inicial',user:'Usuario',item_price_override:'Precio de producto',order_update:'Modificación de orden'};
const scalar=(v:unknown)=>v===null||v===undefined?'—':typeof v==='boolean'?(v?'Sí':'No'):typeof v==='object'?'Ver desglose':String(v);
const labels:Record<string,string>={name:'Nombre',full_name:'Nombre',currency_code:'Moneda',account_kind:'Tipo',institution_name:'Institución',owner_name:'Titular',notes:'Notas',is_active:'Activo',closure_kind:'Cierre',requires_zero_difference:'Exige diferencia cero',generates_transfer_on_close:'Transfiere al cerrar',default_target_money_account_id:'Cuenta destino',counted_amount:'Saldo contado',baseline_date:'Fecha base',reason:'Motivo',roles:'Roles',role:'Rol',payment_method_code:'Método',can_view_account:'Ver cuenta',can_share_with_client:'Compartir',can_report_payment:'Reportar',can_confirm_payment:'Confirmar',auto_confirms_report:'Confirmar automáticamente',review_required:'Revisión',review_roles:'Revisores',receives_commissions:'Comisiones'};
function AuditValue({value}:{value:unknown}){
 if(Array.isArray(value))return <div className="space-y-2">{value.map((item,index)=><div key={index} className="border-t border-[#292937] pt-1"><AuditValue value={item}/></div>)}</div>;
 if(!value||typeof value!=='object')return <span className="break-words text-[11px]">{scalar(value)}</span>;
 return <dl className="space-y-1">{Object.entries(record(value)).filter(([key])=>key==='default_target_money_account_id'||(!key.endsWith('_id')&&!['id','operation_id','created_by','created_at','updated_at','money_account_id','user_id'].includes(key))).map(([key,v])=><div key={key} className="min-w-0"><dt className="text-[11px] text-[#9B9BA7]">{labels[key]||key.replaceAll('_',' ')}</dt><dd className="break-words text-[11px] text-[#BDBDC7]">{v&&typeof v==='object'?<AuditValue value={v}/>:scalar(v)}</dd></div>)}</dl>;
}
export default async function AuditPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 await requireAdminContext();const raw=await searchParams,params=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,Array.isArray(v)?v[0]:v]));let data;
 try{data=await loadAdminAdjustmentAudit(params);}catch(error){return <AdminReadError title="Historial de ajustes" message={error instanceof Error?error.message:'No se pudo consultar.'}/>;}
 const kind=params.kind==='configuration'?'configuration':'orders',today=getCaracasDateKey(new Date());
 const href=(page:number)=>'/app/admin/reportes/ajustes?'+new URLSearchParams({...Object.fromEntries(Object.entries(params).filter((entry):entry is [string,string]=>typeof entry[1]==='string')),consultar:'1',page:String(page)});
 return <div className="space-y-3"><h1 className="text-lg font-semibold text-[#DEDEE6]">Historial de ajustes</h1><nav className="flex flex-wrap gap-3 text-xs"><Link href="/app/admin/reportes/ajustes?kind=orders" prefetch={false} className="inline-flex min-h-11 items-center text-[#FFFF00]">Órdenes</Link><Link href="/app/admin/reportes/ajustes?kind=configuration" prefetch={false} className="inline-flex min-h-11 items-center text-[#FFFF00]">Configuración</Link></nav>
 <WorkspaceForm action="/app/admin/reportes/ajustes" method="get" className={adminPanel+' flex flex-wrap items-end gap-2'}><input type="hidden" name="consultar" value="1"/><input type="hidden" name="kind" value={kind}/>
 {kind==='orders'?<><label className="grid gap-1 text-xs">Desde<input name="from" type="date" defaultValue={params.from||today} required className={input}/></label><label className="grid gap-1 text-xs">Hasta<input name="to" type="date" defaultValue={params.to||today} required className={input}/></label><label className="grid gap-1 text-xs">Orden corta<input name="order" type="number" min="1" defaultValue={params.order||''} className={input+' w-28'}/></label><label className="grid gap-1 text-xs">Tipo<select name="type" defaultValue={params.type||''} className={input}><option value="">Todos</option><option value="item_price_override">Precio</option><option value="order_update">Edición de orden</option>{Array.from(new Set(data.rows.map(r=>String(r.adjustment_type)))).filter(t=>t!=='item_price_override'&&t!=='order_update').map(t=><option key={t} value={t}>{titles[t]||t.replaceAll('_',' ')}</option>)}</select></label><label className="grid gap-1 text-xs">Responsable<select name="actor" defaultValue={params.actor||''} className={input}><option value="">Todos</option>{data.actors.map(a=><option key={String(a.id)} value={String(a.id)}>{String(a.full_name||'Usuario')}</option>)}</select></label></>:null}
 <button className="min-h-11 rounded-lg bg-[#FFFF00] px-3 text-xs font-semibold text-black">Consultar historial</button></WorkspaceForm>
 {data.queried?<section className={adminPanel}><p className="mb-2 text-[11px] text-[#9B9BA7]">{data.rows.length} registros en esta página</p>{data.rows.map(r=>{
  const payload=record(r.payload),old=r.previous_value,next=r.next_value;
  const operation=String(r.command||r.adjustment_type||''),orderId=Number(r.order_id),actor=String(r.actor_name||data.actors.find(a=>a.id===r.created_by_user_id)?.full_name||'Usuario');
  return <details key={String(r.id||r.operation_id)} className="border-t border-[#292937]"><summary className="flex min-h-11 cursor-pointer flex-wrap items-center justify-between gap-2 py-2 text-xs"><span>{titles[operation]||operation.replaceAll('_',' ')}{orderId>0?' · #'+orderId:' · '+String(r.entity_name||'Configuración')}</span><span className="text-[11px] text-[#9B9BA7]">{actor} · {new Intl.DateTimeFormat('es-VE',{dateStyle:'short',timeStyle:'short',timeZone:'America/Caracas'}).format(new Date(String(r.created_at)))}</span></summary><div className="space-y-2 pb-3 text-xs">{orderId>0?<Link href={'/app/admin/ordenes?openOrder='+orderId} prefetch={false} className="inline-flex min-h-11 items-center text-[#FFFF00]">Abrir orden #{orderId} →</Link>:null}<p>{String(r.reason||r.notes||payload.reason||'Cambio registrado')}</p>
  {kind==='orders'?<dl className="grid grid-cols-2 gap-2">{[['Producto',payload.product_name],['Precio anterior USD',payload.original_unit_price_usd],['Precio nuevo USD',payload.override_unit_price_usd],['Diferencia USD',payload.delta_usd],['Cantidad',payload.qty],['Comisión',payload.commission_mode],['Porcentaje',payload.commission_value]].filter(([,v])=>v!==undefined).map(([label,v])=><div key={String(label)}><dt className="text-[11px] text-[#9B9BA7]">{String(label)}</dt><dd>{scalar(v)}</dd></div>)}</dl>:<div className="grid gap-2 sm:grid-cols-2">{[['Antes',old],['Después',next]].map(([label,value])=><div key={String(label)} className="rounded-lg border border-[#292937] p-2"><h3 className="mb-1 font-medium">{String(label)}</h3><AuditValue value={value}/></div>)}</div>}
  </div></details>
 })}{!data.rows.length?<p className="text-xs text-[#9B9BA7]">No hay ajustes con estos filtros.</p>:null}<nav className="mt-2 flex justify-between gap-2 text-xs">{data.page>1?<Link href={href(data.page-1)} prefetch={false} className="inline-flex min-h-11 items-center underline">Anterior</Link>:<span/>}<span className="content-center">Página {data.page}</span>{data.hasNext?<Link href={href(data.page+1)} prefetch={false} className="inline-flex min-h-11 items-center underline">Siguiente</Link>:<span/>}</nav></section>:<p className="text-xs text-[#9B9BA7]">El historial se consulta por separado; no carga al abrir Administración.</p>}
 </div>;
}
