-- Isolated PostgreSQL test schema, inspected against production on 2026-10-01.
-- Contains no production records or credentials.
create schema auth; create schema app_private;
create role anon; create role authenticated; create role service_role;
grant usage on schema public, auth to anon, authenticated, service_role;
create type public.user_role as enum ('admin','master','advisor','kitchen','driver','counter');
create type public.currency_code as enum ('USD','VES');
create type public.account_kind as enum ('bank','cash','wallet','pos','fund','other');
create table auth.users(id uuid primary key);
create table public.payment_methods(code text primary key);
insert into public.payment_methods values ('payment_mobile'),('transfer'),('zelle'),('wallet_usd'),('cash_usd'),('cash_ves'),('pos'),('retention');
create table public.money_account_closure_baselines (
 id bigserial not null,
 money_account_id bigint not null,
 baseline_date date not null,
 baseline_at timestamp with time zone not null,
 currency_code text not null,
 exchange_rate_ves_per_usd numeric(18,6),
 expected_amount numeric(18,2) default 0 not null,
 counted_amount numeric(18,2) default 0 not null,
 difference_amount numeric(18,2) default 0 not null,
 expected_amount_usd numeric(18,2) default 0 not null,
 counted_amount_usd numeric(18,2) default 0 not null,
 difference_amount_usd numeric(18,2) default 0 not null,
 status text default 'active'::text not null,
 reason text,
 notes text,
 created_by_user_id uuid not null,
 created_at timestamp with time zone default now() not null,
 voided_by_user_id uuid,
 voided_at timestamp with time zone,
 void_reason text
);
create table public.money_account_closure_profiles (
 id bigserial not null,
 money_account_id bigint not null,
 closure_kind text not null,
 requires_zero_difference boolean default false not null,
 allows_classified_difference boolean default true not null,
 generates_transfer_on_close boolean default false not null,
 default_target_money_account_id bigint,
 baseline_required boolean default true not null,
 notes text,
 created_at timestamp with time zone default now() not null,
 updated_at timestamp with time zone default now() not null
);
create table public.money_account_payment_rules (
 id bigint generated by default as identity not null,
 money_account_id bigint not null,
 role public.user_role not null,
 payment_method_code text not null,
 can_view_account boolean default false not null,
 can_share_with_client boolean default false not null,
 can_report_payment boolean default false not null,
 can_confirm_payment boolean default false not null,
 auto_confirms_report boolean default false not null,
 review_required boolean default true not null,
 review_roles public.user_role[] default '{}'::user_role[] not null,
 is_active boolean default true not null,
 notes text,
 created_at timestamp with time zone default now() not null,
 updated_at timestamp with time zone default now() not null
);
create table public.money_accounts (
 id bigserial not null,
 name text not null,
 currency_code public.currency_code not null,
 account_kind public.account_kind not null,
 institution_name text,
 owner_name text,
 notes text,
 is_active boolean default true not null,
 created_at timestamp with time zone default now() not null,
 created_by_user_id uuid
);
create table public.profiles (
 id uuid not null,
 full_name text not null,
 is_active boolean default true not null,
 created_at timestamp with time zone default now() not null,
 receives_commissions boolean default false not null
);
create table public.user_roles (
 user_id uuid not null,
 role public.user_role not null,
 created_at timestamp with time zone default now() not null
);
alter table public.money_accounts add constraint money_accounts_name_currency_uk UNIQUE (name, currency_code);
alter table public.money_accounts add constraint money_accounts_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.user_roles add constraint user_roles_pkey PRIMARY KEY (user_id, role);
alter table public.user_roles add constraint user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.money_account_payment_rules add constraint money_account_payment_rules_confirm_ck CHECK (((auto_confirms_report = false) OR (can_confirm_payment = true)));
alter table public.money_account_payment_rules add constraint money_account_payment_rules_money_account_id_fkey FOREIGN KEY (money_account_id) REFERENCES money_accounts(id) ON DELETE CASCADE;
alter table public.money_account_payment_rules add constraint money_account_payment_rules_payment_method_code_fkey FOREIGN KEY (payment_method_code) REFERENCES payment_methods(code) ON DELETE RESTRICT;
alter table public.money_account_payment_rules add constraint money_account_payment_rules_pkey PRIMARY KEY (id);
alter table public.money_account_payment_rules add constraint money_account_payment_rules_review_ck CHECK ((((auto_confirms_report = true) AND (review_required = false) AND (cardinality(review_roles) = 0)) OR ((auto_confirms_report = false) AND (((review_required = true) AND (cardinality(review_roles) > 0)) OR (review_required = false)))));
alter table public.money_account_closure_profiles add constraint money_account_closure_profile_default_target_money_account_fkey FOREIGN KEY (default_target_money_account_id) REFERENCES money_accounts(id);
alter table public.money_account_closure_profiles add constraint money_account_closure_profiles_account_unique UNIQUE (money_account_id);
alter table public.money_account_closure_profiles add constraint money_account_closure_profiles_kind_check CHECK ((closure_kind = ANY (ARRAY['bank'::text, 'cash'::text, 'pos'::text, 'wallet_usd'::text, 'retention'::text, 'fund'::text, 'other'::text])));
alter table public.money_account_closure_profiles add constraint money_account_closure_profiles_money_account_id_fkey FOREIGN KEY (money_account_id) REFERENCES money_accounts(id) ON DELETE CASCADE;
alter table public.money_account_closure_profiles add constraint money_account_closure_profiles_pkey PRIMARY KEY (id);
alter table public.money_account_closure_baselines add constraint money_account_closure_baselines_currency_check CHECK ((currency_code = ANY (ARRAY['USD'::text, 'VES'::text])));
alter table public.money_account_closure_baselines add constraint money_account_closure_baselines_money_account_id_fkey FOREIGN KEY (money_account_id) REFERENCES money_accounts(id) ON DELETE CASCADE;
alter table public.money_account_closure_baselines add constraint money_account_closure_baselines_pkey PRIMARY KEY (id);
alter table public.money_account_closure_baselines add constraint money_account_closure_baselines_status_check CHECK ((status = ANY (ARRAY['active'::text, 'superseded'::text, 'voided'::text])));
alter table public.money_account_closure_baselines add constraint money_account_closure_baselines_ves_rate_check CHECK (((currency_code <> 'VES'::text) OR (exchange_rate_ves_per_usd IS NOT NULL)));
CREATE UNIQUE INDEX idx_money_account_closure_baselines_one_active ON public.money_account_closure_baselines USING btree (money_account_id) WHERE (status = 'active'::text);
CREATE INDEX idx_money_account_closure_baselines_account_date ON public.money_account_closure_baselines USING btree (money_account_id, baseline_at DESC);
CREATE UNIQUE INDEX money_account_payment_rules_unique_idx ON public.money_account_payment_rules USING btree (money_account_id, role, payment_method_code);
CREATE INDEX money_account_payment_rules_role_method_idx ON public.money_account_payment_rules USING btree (role, payment_method_code, is_active);
CREATE INDEX money_account_payment_rules_account_idx ON public.money_account_payment_rules USING btree (money_account_id, is_active);
CREATE INDEX idx_money_account_payment_rules_lookup ON public.money_account_payment_rules USING btree (money_account_id, role, payment_method_code, is_active);
create table public.money_movements(money_account_id bigint, direction text, amount numeric, amount_usd_equivalent numeric, status text, movement_date date);
create function auth.uid() returns uuid language sql stable as $f$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $f$;
create function public.has_role(p_role text) returns boolean language sql stable security definer set search_path='' as $f$ select exists(select 1 from public.user_roles where user_id=(select auth.uid()) and role::text=p_role) $f$;

