create table if not exists public.user_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text null,
  scope text not null default 'app',
  is_active boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists user_push_subscriptions_user_idx
  on public.user_push_subscriptions(user_id, is_active, last_seen_at desc);

create index if not exists user_push_subscriptions_active_idx
  on public.user_push_subscriptions(is_active, last_seen_at desc);

alter table public.user_push_subscriptions enable row level security;

drop policy if exists "user_push_subscriptions_select_own" on public.user_push_subscriptions;
create policy "user_push_subscriptions_select_own"
on public.user_push_subscriptions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_push_subscriptions_insert_own" on public.user_push_subscriptions;
create policy "user_push_subscriptions_insert_own"
on public.user_push_subscriptions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_push_subscriptions_update_own" on public.user_push_subscriptions;
create policy "user_push_subscriptions_update_own"
on public.user_push_subscriptions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_push_subscriptions_delete_own" on public.user_push_subscriptions;
create policy "user_push_subscriptions_delete_own"
on public.user_push_subscriptions
for delete
to authenticated
using (auth.uid() = user_id);
