-- Inventory Phase A: additive foundation.
--
-- This migration does not change order deduction behavior or reinterpret
-- existing balances. It adds the structures needed to migrate safely later.

set lock_timeout = '5s';
set statement_timeout = '60s';

alter table public.inventory_items
  add column tracking_mode text,
  add column consumption_triggers text[],
  add column availability_mode text,
  add column target_stock_units numeric,
  add column shelf_life_days integer,
  add column merged_into_item_id bigint,
  add column primary_count_frequency text,
  add column primary_count_role public.user_role,
  add column low_stock_inclusive boolean not null default true;

alter table public.inventory_items
  add constraint inventory_items_tracking_mode_check
    check (
      tracking_mode is null
      or tracking_mode in ('transactional', 'periodic_count', 'not_tracked')
    ),
  add constraint inventory_items_consumption_triggers_check
    check (
      consumption_triggers is null
      or (
        consumption_triggers <@ array['sale', 'production', 'manual_issue']::text[]
        and array_position(consumption_triggers, null) is null
      )
    ),
  add constraint inventory_items_availability_mode_check
    check (
      availability_mode is null
      or availability_mode in ('on_hand_only', 'immediate_recipe', 'scheduled_recipe')
    ),
  add constraint inventory_items_target_stock_units_check
    check (target_stock_units is null or target_stock_units >= 0),
  add constraint inventory_items_shelf_life_days_check
    check (shelf_life_days is null or shelf_life_days >= 0),
  add constraint inventory_items_primary_count_frequency_check
    check (
      primary_count_frequency is null
      or primary_count_frequency in ('per_shift', 'daily', 'weekly', 'biweekly', 'monthly')
    ),
  add constraint inventory_items_merged_into_not_self_check
    check (merged_into_item_id is null or merged_into_item_id <> id),
  add constraint inventory_items_merged_into_item_id_fkey
    foreign key (merged_into_item_id)
    references public.inventory_items(id)
    on delete restrict;

create index inventory_items_merged_into_item_id_idx
  on public.inventory_items using btree (merged_into_item_id)
  where merged_into_item_id is not null;

alter table public.product_inventory_links
  add constraint product_inventory_links_quantity_units_positive_check
    check (quantity_units > 0),
  add constraint product_inventory_links_deduction_mode_check
    check (deduction_mode in ('self_link', 'recipe'));

create unique index product_inventory_links_active_item_uidx
  on public.product_inventory_links using btree (product_id, inventory_item_id)
  where is_active;

alter table public.inventory_recipes
  add column lead_time_minutes integer not null default 0,
  add column production_multiple numeric not null default 1,
  add column version integer not null default 1;

alter table public.inventory_recipes
  add constraint inventory_recipes_output_quantity_positive_check
    check (output_quantity_units > 0),
  add constraint inventory_recipes_lead_time_nonnegative_check
    check (lead_time_minutes >= 0),
  add constraint inventory_recipes_production_multiple_positive_check
    check (production_multiple > 0),
  add constraint inventory_recipes_version_positive_check
    check (version >= 1);

create unique index inventory_recipes_one_active_output_kind_uidx
  on public.inventory_recipes using btree (output_inventory_item_id, recipe_kind)
  where is_active;

alter table public.inventory_recipe_components
  add constraint inventory_recipe_components_quantity_positive_check
    check (quantity_units > 0);

create index inventory_recipe_components_input_item_idx
  on public.inventory_recipe_components using btree (input_inventory_item_id);

alter table public.order_item_components
  add column component_name_snapshot text;

create table public.inventory_item_presentations (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null,
  name text not null,
  base_units_per_presentation numeric not null,
  allows_fractional_quantity boolean not null default false,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint inventory_item_presentations_inventory_item_id_fkey
    foreign key (inventory_item_id)
    references public.inventory_items(id)
    on delete cascade,
  constraint inventory_item_presentations_name_not_blank_check
    check (btrim(name) <> ''),
  constraint inventory_item_presentations_base_units_positive_check
    check (base_units_per_presentation > 0)
);

create unique index inventory_item_presentations_item_name_uidx
  on public.inventory_item_presentations using btree (inventory_item_id, lower(name));

create table public.inventory_lots (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null,
  lot_code text,
  lot_kind text not null,
  received_or_produced_at timestamp with time zone not null,
  expires_at timestamp with time zone,
  initial_quantity_units numeric not null,
  status text not null default 'open'::text,
  closed_at timestamp with time zone,
  notes text,
  created_by_user_id uuid not null,
  created_at timestamp with time zone not null default now(),
  constraint inventory_lots_inventory_item_id_fkey
    foreign key (inventory_item_id)
    references public.inventory_items(id)
    on delete restrict,
  constraint inventory_lots_created_by_user_id_fkey
    foreign key (created_by_user_id)
    references public.profiles(id)
    on delete restrict,
  constraint inventory_lots_kind_check
    check (lot_kind in ('receipt', 'production', 'return', 'opening_balance')),
  constraint inventory_lots_status_check
    check (status in ('open', 'depleted', 'quarantined', 'expired', 'closed')),
  constraint inventory_lots_initial_quantity_positive_check
    check (initial_quantity_units > 0),
  constraint inventory_lots_expiry_after_origin_check
    check (expires_at is null or expires_at > received_or_produced_at),
  constraint inventory_lots_code_not_blank_check
    check (lot_code is null or btrim(lot_code) <> '')
);

create index inventory_lots_inventory_item_id_idx
  on public.inventory_lots using btree (inventory_item_id);

create index inventory_lots_created_by_user_id_idx
  on public.inventory_lots using btree (created_by_user_id);

create index inventory_lots_open_expiry_idx
  on public.inventory_lots using btree (inventory_item_id, expires_at)
  where status = 'open';

create unique index inventory_lots_item_code_uidx
  on public.inventory_lots using btree (inventory_item_id, lot_code)
  where lot_code is not null;

create table public.inventory_planned_flows (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null,
  flow_type text not null,
  quantity_units numeric,
  effective_at timestamp with time zone,
  status text not null default 'draft'::text,
  order_id bigint,
  inventory_recipe_id bigint,
  depends_on_flow_id bigint,
  notes text,
  created_by_user_id uuid not null,
  resolved_by_user_id uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint inventory_planned_flows_inventory_item_id_fkey
    foreign key (inventory_item_id)
    references public.inventory_items(id)
    on delete restrict,
  constraint inventory_planned_flows_order_id_fkey
    foreign key (order_id)
    references public.orders(id)
    on delete set null,
  constraint inventory_planned_flows_inventory_recipe_id_fkey
    foreign key (inventory_recipe_id)
    references public.inventory_recipes(id)
    on delete set null,
  constraint inventory_planned_flows_depends_on_flow_id_fkey
    foreign key (depends_on_flow_id)
    references public.inventory_planned_flows(id)
    on delete restrict,
  constraint inventory_planned_flows_created_by_user_id_fkey
    foreign key (created_by_user_id)
    references public.profiles(id)
    on delete restrict,
  constraint inventory_planned_flows_resolved_by_user_id_fkey
    foreign key (resolved_by_user_id)
    references public.profiles(id)
    on delete restrict,
  constraint inventory_planned_flows_type_check
    check (flow_type in (
      'order_commitment',
      'expected_receipt',
      'planned_production',
      'declared_unavailability'
    )),
  constraint inventory_planned_flows_status_check
    check (status in ('draft', 'active', 'fulfilled', 'cancelled', 'failed')),
  constraint inventory_planned_flows_quantity_check
    check (
      (flow_type = 'declared_unavailability' and quantity_units is null)
      or (
        flow_type <> 'declared_unavailability'
        and quantity_units is not null
        and quantity_units > 0
      )
    ),
  constraint inventory_planned_flows_effective_at_check
    check (flow_type = 'declared_unavailability' or effective_at is not null),
  constraint inventory_planned_flows_dependency_not_self_check
    check (depends_on_flow_id is null or depends_on_flow_id <> id),
  constraint inventory_planned_flows_resolution_check
    check (
      (resolved_at is null and resolved_by_user_id is null)
      or (resolved_at is not null and resolved_by_user_id is not null)
    )
);

create index inventory_planned_flows_active_effective_idx
  on public.inventory_planned_flows using btree (inventory_item_id, effective_at)
  where status = 'active';

create index inventory_planned_flows_inventory_item_id_idx
  on public.inventory_planned_flows using btree (inventory_item_id);

create index inventory_planned_flows_order_id_idx
  on public.inventory_planned_flows using btree (order_id)
  where order_id is not null;

create index inventory_planned_flows_recipe_id_idx
  on public.inventory_planned_flows using btree (inventory_recipe_id)
  where inventory_recipe_id is not null;

create index inventory_planned_flows_depends_on_flow_id_idx
  on public.inventory_planned_flows using btree (depends_on_flow_id)
  where depends_on_flow_id is not null;

create index inventory_planned_flows_created_by_user_id_idx
  on public.inventory_planned_flows using btree (created_by_user_id);

create index inventory_planned_flows_resolved_by_user_id_idx
  on public.inventory_planned_flows using btree (resolved_by_user_id)
  where resolved_by_user_id is not null;

create table public.inventory_counts (
  id bigint generated by default as identity primary key,
  count_kind text not null,
  status text not null default 'open'::text,
  responsible_role public.user_role not null,
  parent_count_id bigint,
  requested_by_user_id uuid,
  created_by_user_id uuid not null,
  due_at timestamp with time zone,
  submitted_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  reviewed_by_user_id uuid,
  notes text,
  created_at timestamp with time zone not null default now(),
  constraint inventory_counts_parent_count_id_fkey
    foreign key (parent_count_id)
    references public.inventory_counts(id)
    on delete restrict,
  constraint inventory_counts_requested_by_user_id_fkey
    foreign key (requested_by_user_id)
    references public.profiles(id)
    on delete restrict,
  constraint inventory_counts_created_by_user_id_fkey
    foreign key (created_by_user_id)
    references public.profiles(id)
    on delete restrict,
  constraint inventory_counts_reviewed_by_user_id_fkey
    foreign key (reviewed_by_user_id)
    references public.profiles(id)
    on delete restrict,
  constraint inventory_counts_kind_check
    check (count_kind in ('shift_change', 'requested', 'recount', 'periodic')),
  constraint inventory_counts_status_check
    check (status in (
      'open',
      'submitted',
      'accepted',
      'recount_requested',
      'expired',
      'cancelled'
    )),
  constraint inventory_counts_parent_not_self_check
    check (parent_count_id is null or parent_count_id <> id),
  constraint inventory_counts_review_check
    check (
      (reviewed_at is null and reviewed_by_user_id is null)
      or (reviewed_at is not null and reviewed_by_user_id is not null)
    )
);

create index inventory_counts_parent_count_id_idx
  on public.inventory_counts using btree (parent_count_id)
  where parent_count_id is not null;

create index inventory_counts_requested_by_user_id_idx
  on public.inventory_counts using btree (requested_by_user_id)
  where requested_by_user_id is not null;

create index inventory_counts_created_by_user_id_idx
  on public.inventory_counts using btree (created_by_user_id);

create index inventory_counts_reviewed_by_user_id_idx
  on public.inventory_counts using btree (reviewed_by_user_id)
  where reviewed_by_user_id is not null;

create index inventory_counts_status_due_at_idx
  on public.inventory_counts using btree (status, due_at);

create table public.inventory_count_lines (
  id bigint generated by default as identity primary key,
  inventory_count_id bigint not null,
  inventory_item_id bigint not null,
  expected_quantity_units numeric not null,
  counted_quantity_units numeric,
  difference_quantity_units numeric generated always as (
    counted_quantity_units - expected_quantity_units
  ) stored,
  line_status text not null default 'pending'::text,
  note text,
  movement_id bigint,
  recounted_from_line_id bigint,
  counted_by_user_id uuid,
  counted_at timestamp with time zone,
  reviewed_by_user_id uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  constraint inventory_count_lines_inventory_count_id_fkey
    foreign key (inventory_count_id)
    references public.inventory_counts(id)
    on delete cascade,
  constraint inventory_count_lines_inventory_item_id_fkey
    foreign key (inventory_item_id)
    references public.inventory_items(id)
    on delete restrict,
  constraint inventory_count_lines_movement_id_fkey
    foreign key (movement_id)
    references public.inventory_movements(id)
    on delete restrict,
  constraint inventory_count_lines_recounted_from_line_id_fkey
    foreign key (recounted_from_line_id)
    references public.inventory_count_lines(id)
    on delete restrict,
  constraint inventory_count_lines_counted_by_user_id_fkey
    foreign key (counted_by_user_id)
    references public.profiles(id)
    on delete restrict,
  constraint inventory_count_lines_reviewed_by_user_id_fkey
    foreign key (reviewed_by_user_id)
    references public.profiles(id)
    on delete restrict,
  constraint inventory_count_lines_count_item_key
    unique (inventory_count_id, inventory_item_id),
  constraint inventory_count_lines_counted_nonnegative_check
    check (counted_quantity_units is null or counted_quantity_units >= 0),
  constraint inventory_count_lines_status_check
    check (line_status in (
      'pending',
      'submitted',
      'accepted',
      'recount_requested',
      'superseded'
    )),
  constraint inventory_count_lines_recount_not_self_check
    check (recounted_from_line_id is null or recounted_from_line_id <> id),
  constraint inventory_count_lines_counted_audit_check
    check (
      (counted_quantity_units is null and counted_by_user_id is null and counted_at is null)
      or (counted_quantity_units is not null and counted_by_user_id is not null and counted_at is not null)
    ),
  constraint inventory_count_lines_review_audit_check
    check (
      (reviewed_at is null and reviewed_by_user_id is null)
      or (reviewed_at is not null and reviewed_by_user_id is not null)
    )
);

create index inventory_count_lines_inventory_item_id_idx
  on public.inventory_count_lines using btree (inventory_item_id);

create index inventory_count_lines_movement_id_idx
  on public.inventory_count_lines using btree (movement_id)
  where movement_id is not null;

create index inventory_count_lines_recounted_from_line_id_idx
  on public.inventory_count_lines using btree (recounted_from_line_id)
  where recounted_from_line_id is not null;

create index inventory_count_lines_counted_by_user_id_idx
  on public.inventory_count_lines using btree (counted_by_user_id)
  where counted_by_user_id is not null;

create index inventory_count_lines_reviewed_by_user_id_idx
  on public.inventory_count_lines using btree (reviewed_by_user_id)
  where reviewed_by_user_id is not null;

alter table public.inventory_movements
  add column operation_id uuid,
  add column reversal_of_movement_id bigint,
  add column inventory_lot_id bigint;

alter table public.inventory_movements
  add constraint inventory_movements_reversal_not_self_check
    check (reversal_of_movement_id is null or reversal_of_movement_id <> id),
  add constraint inventory_movements_reversal_of_movement_id_fkey
    foreign key (reversal_of_movement_id)
    references public.inventory_movements(id)
    on delete restrict,
  add constraint inventory_movements_inventory_lot_id_fkey
    foreign key (inventory_lot_id)
    references public.inventory_lots(id)
    on delete restrict;

create index inventory_movements_operation_id_idx
  on public.inventory_movements using btree (operation_id)
  where operation_id is not null;

create unique index inventory_movements_one_reversal_uidx
  on public.inventory_movements using btree (reversal_of_movement_id)
  where reversal_of_movement_id is not null;

create index inventory_movements_inventory_lot_id_idx
  on public.inventory_movements using btree (inventory_lot_id)
  where inventory_lot_id is not null;

alter table public.inventory_item_presentations enable row level security;
alter table public.inventory_lots enable row level security;
alter table public.inventory_planned_flows enable row level security;
alter table public.inventory_counts enable row level security;
alter table public.inventory_count_lines enable row level security;

create policy inventory_item_presentations_read_operations
  on public.inventory_item_presentations
  for select
  to authenticated
  using (
    (select public.has_role('admin'))
    or (select public.has_role('master'))
    or (select public.has_role('kitchen'))
    or (select public.has_role('counter'))
  );

create policy inventory_item_presentations_insert_admin
  on public.inventory_item_presentations
  for insert
  to authenticated
  with check ((select public.has_role('admin')));

create policy inventory_item_presentations_update_admin
  on public.inventory_item_presentations
  for update
  to authenticated
  using ((select public.has_role('admin')))
  with check ((select public.has_role('admin')));

create policy inventory_item_presentations_delete_admin
  on public.inventory_item_presentations
  for delete
  to authenticated
  using ((select public.has_role('admin')));

create policy inventory_lots_read_operations
  on public.inventory_lots
  for select
  to authenticated
  using (
    (select public.has_role('admin'))
    or (select public.has_role('master'))
    or (select public.has_role('kitchen'))
  );

create policy inventory_lots_insert_admin
  on public.inventory_lots
  for insert
  to authenticated
  with check ((select public.has_role('admin')));

create policy inventory_lots_update_admin
  on public.inventory_lots
  for update
  to authenticated
  using ((select public.has_role('admin')))
  with check ((select public.has_role('admin')));

create policy inventory_lots_delete_admin
  on public.inventory_lots
  for delete
  to authenticated
  using ((select public.has_role('admin')));

create policy inventory_planned_flows_read_operations
  on public.inventory_planned_flows
  for select
  to authenticated
  using (
    (select public.has_role('admin'))
    or (select public.has_role('master'))
    or (select public.has_role('kitchen'))
    or (select public.has_role('counter'))
  );

create policy inventory_planned_flows_insert_master_admin
  on public.inventory_planned_flows
  for insert
  to authenticated
  with check (
    (select public.has_role('admin'))
    or (select public.has_role('master'))
  );

create policy inventory_planned_flows_update_master_admin
  on public.inventory_planned_flows
  for update
  to authenticated
  using (
    (select public.has_role('admin'))
    or (select public.has_role('master'))
  )
  with check (
    (select public.has_role('admin'))
    or (select public.has_role('master'))
  );

create policy inventory_planned_flows_delete_admin
  on public.inventory_planned_flows
  for delete
  to authenticated
  using ((select public.has_role('admin')));

create policy inventory_counts_read_operations
  on public.inventory_counts
  for select
  to authenticated
  using (
    (select public.has_role('admin'))
    or (select public.has_role('master'))
    or (select public.has_role('kitchen'))
  );

create policy inventory_counts_insert_admin
  on public.inventory_counts
  for insert
  to authenticated
  with check ((select public.has_role('admin')));

create policy inventory_counts_update_admin
  on public.inventory_counts
  for update
  to authenticated
  using ((select public.has_role('admin')))
  with check ((select public.has_role('admin')));

create policy inventory_counts_delete_admin
  on public.inventory_counts
  for delete
  to authenticated
  using ((select public.has_role('admin')));

create policy inventory_count_lines_read_operations
  on public.inventory_count_lines
  for select
  to authenticated
  using (
    (select public.has_role('admin'))
    or (select public.has_role('master'))
    or (select public.has_role('kitchen'))
  );

create policy inventory_count_lines_insert_admin
  on public.inventory_count_lines
  for insert
  to authenticated
  with check ((select public.has_role('admin')));

create policy inventory_count_lines_update_admin
  on public.inventory_count_lines
  for update
  to authenticated
  using ((select public.has_role('admin')))
  with check ((select public.has_role('admin')));

create policy inventory_count_lines_delete_admin
  on public.inventory_count_lines
  for delete
  to authenticated
  using ((select public.has_role('admin')));

revoke all on table public.inventory_item_presentations from anon;
revoke all on table public.inventory_lots from anon;
revoke all on table public.inventory_planned_flows from anon;
revoke all on table public.inventory_counts from anon;
revoke all on table public.inventory_count_lines from anon;

grant select, insert, update, delete
  on table public.inventory_item_presentations,
           public.inventory_lots,
           public.inventory_planned_flows,
           public.inventory_counts,
           public.inventory_count_lines
  to authenticated;

grant all
  on table public.inventory_item_presentations,
           public.inventory_lots,
           public.inventory_planned_flows,
           public.inventory_counts,
           public.inventory_count_lines
  to service_role;

revoke all on sequence public.inventory_item_presentations_id_seq from anon;
revoke all on sequence public.inventory_lots_id_seq from anon;
revoke all on sequence public.inventory_planned_flows_id_seq from anon;
revoke all on sequence public.inventory_counts_id_seq from anon;
revoke all on sequence public.inventory_count_lines_id_seq from anon;

grant usage, select
  on sequence public.inventory_item_presentations_id_seq,
              public.inventory_lots_id_seq,
              public.inventory_planned_flows_id_seq,
              public.inventory_counts_id_seq,
              public.inventory_count_lines_id_seq
  to authenticated, service_role;
