-- Inventory schema baseline.
--
-- These objects already exist in the linked production database but were
-- created outside the tracked migration history. This migration makes the
-- current inventory schema reproducible without changing its behavior.

alter table public.products
  add column inventory_enabled boolean not null default false,
  add column inventory_kind text not null default 'finished_good'::text,
  add column inventory_unit_name text not null default 'pieza'::text,
  add column packaging_name text,
  add column packaging_size numeric,
  add column current_stock_units numeric not null default 0,
  add column low_stock_threshold numeric,
  add column inventory_deduction_mode text not null default 'self'::text,
  add column inventory_group text not null default 'other'::text;

alter table public.products
  add constraint products_inventory_kind_check
    check (inventory_kind = any (array[
      'raw_material'::text,
      'prepared_base'::text,
      'finished_good'::text
    ])),
  add constraint products_inventory_deduction_mode_check
    check (inventory_deduction_mode = any (array[
      'self'::text,
      'composition'::text
    ])),
  add constraint products_inventory_group_check
    check (inventory_group = any (array[
      'raw'::text,
      'fried'::text,
      'prefried'::text,
      'sauces'::text,
      'packaging'::text,
      'other'::text
    ]));

create table public.inventory_items (
  id bigint generated by default as identity not null,
  name text not null,
  inventory_kind text not null default 'finished_stock'::text,
  unit_name text not null default 'pieza'::text,
  packaging_name text,
  packaging_size numeric,
  current_stock_units numeric not null default 0,
  low_stock_threshold numeric,
  is_active boolean not null default true,
  notes text,
  created_at timestamp with time zone not null default now(),
  inventory_group text not null default 'other'::text,
  constraint inventory_items_pkey primary key (id),
  constraint inventory_items_kind_check
    check (inventory_kind = any (array[
      'raw_material'::text,
      'prepared_base'::text,
      'finished_stock'::text,
      'packaging'::text
    ])),
  constraint inventory_items_group_check
    check (inventory_group = any (array[
      'raw'::text,
      'fried'::text,
      'prefried'::text,
      'sauces'::text,
      'packaging'::text,
      'other'::text
    ]))
);

create table public.product_inventory_links (
  id bigint generated by default as identity not null,
  product_id bigint not null,
  inventory_item_id bigint not null,
  deduction_mode text not null default 'self_link'::text,
  quantity_units numeric not null default 1,
  sort_order integer not null default 0,
  notes text,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  constraint product_inventory_links_pkey primary key (id),
  constraint product_inventory_links_product_id_fkey
    foreign key (product_id) references public.products(id) on delete cascade,
  constraint product_inventory_links_inventory_item_id_fkey
    foreign key (inventory_item_id) references public.inventory_items(id) on delete cascade
);

create table public.inventory_recipes (
  id bigint generated by default as identity not null,
  output_inventory_item_id bigint not null,
  recipe_kind text not null,
  output_quantity_units numeric not null default 1,
  notes text,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  constraint inventory_recipes_pkey primary key (id),
  constraint inventory_recipes_kind_check
    check (recipe_kind = any (array[
      'production'::text,
      'packaging'::text
    ])),
  constraint inventory_recipes_output_inventory_item_id_fkey
    foreign key (output_inventory_item_id) references public.inventory_items(id) on delete cascade
);

create table public.inventory_recipe_components (
  id bigint generated by default as identity not null,
  recipe_id bigint not null,
  input_inventory_item_id bigint not null,
  quantity_units numeric not null,
  sort_order integer not null default 0,
  constraint inventory_recipe_components_pkey primary key (id),
  constraint inventory_recipe_components_recipe_id_fkey
    foreign key (recipe_id) references public.inventory_recipes(id) on delete cascade,
  constraint inventory_recipe_components_input_inventory_item_id_fkey
    foreign key (input_inventory_item_id) references public.inventory_items(id) on delete cascade
);

create table public.inventory_movements (
  id bigint generated by default as identity not null,
  inventory_item_id bigint not null,
  movement_type text not null,
  quantity_units numeric not null,
  reason_code text,
  notes text,
  order_id bigint,
  created_at timestamp with time zone not null default now(),
  created_by_user_id uuid not null,
  constraint inventory_movements_pkey primary key (id),
  constraint inventory_movements_type_check
    check (movement_type = any (array[
      'inbound'::text,
      'sale_out'::text,
      'damage'::text,
      'waste'::text,
      'manual_adjustment'::text,
      'stock_count'::text,
      'production_out'::text,
      'production_in'::text,
      'pack_out'::text,
      'pack_in'::text
    ])),
  constraint inventory_movements_inventory_item_id_fkey
    foreign key (inventory_item_id) references public.inventory_items(id) on delete cascade,
  constraint inventory_movements_order_id_fkey
    foreign key (order_id) references public.orders(id) on delete set null
);

create index product_inventory_links_product_id_idx
  on public.product_inventory_links using btree (product_id);

create index product_inventory_links_inventory_item_id_idx
  on public.product_inventory_links using btree (inventory_item_id);

create index inventory_recipes_output_item_idx
  on public.inventory_recipes using btree (output_inventory_item_id);

create index inventory_recipe_components_recipe_idx
  on public.inventory_recipe_components using btree (recipe_id);

create index inventory_movements_created_at_idx
  on public.inventory_movements using btree (created_at desc);

create index inventory_movements_item_created_at_idx
  on public.inventory_movements using btree (inventory_item_id, created_at desc);

create index inventory_movements_item_id_idx
  on public.inventory_movements using btree (inventory_item_id);

create index inventory_movements_order_id_idx
  on public.inventory_movements using btree (order_id);

alter table public.inventory_items enable row level security;
alter table public.product_inventory_links enable row level security;
alter table public.inventory_recipes enable row level security;
alter table public.inventory_recipe_components enable row level security;
alter table public.inventory_movements enable row level security;

create policy inventory_items_select_authenticated
  on public.inventory_items
  as permissive
  for select
  to authenticated
  using (true);

create policy inventory_items_write_master_admin
  on public.inventory_items
  as permissive
  for all
  to authenticated
  using (public.is_master_or_admin())
  with check (public.is_master_or_admin());

create policy product_inventory_links_select_authenticated
  on public.product_inventory_links
  as permissive
  for select
  to authenticated
  using (true);

create policy product_inventory_links_write_master_admin
  on public.product_inventory_links
  as permissive
  for all
  to authenticated
  using (public.is_master_or_admin())
  with check (public.is_master_or_admin());

create policy inventory_recipes_select_authenticated
  on public.inventory_recipes
  as permissive
  for select
  to authenticated
  using (true);

create policy inventory_recipes_write_master_admin
  on public.inventory_recipes
  as permissive
  for all
  to authenticated
  using (public.is_master_or_admin())
  with check (public.is_master_or_admin());

create policy inventory_recipe_components_select_authenticated
  on public.inventory_recipe_components
  as permissive
  for select
  to authenticated
  using (true);

create policy inventory_recipe_components_write_master_admin
  on public.inventory_recipe_components
  as permissive
  for all
  to authenticated
  using (public.is_master_or_admin())
  with check (public.is_master_or_admin());

create policy inventory_movements_select_authenticated
  on public.inventory_movements
  as permissive
  for select
  to authenticated
  using (true);

create policy inventory_movements_write_master_admin
  on public.inventory_movements
  as permissive
  for all
  to authenticated
  using (public.is_master_or_admin())
  with check (public.is_master_or_admin());

grant all on table public.inventory_items to anon, authenticated, service_role;
grant all on table public.product_inventory_links to anon, authenticated, service_role;
grant all on table public.inventory_recipes to anon, authenticated, service_role;
grant all on table public.inventory_recipe_components to anon, authenticated, service_role;
grant all on table public.inventory_movements to anon, authenticated, service_role;

grant all on sequence public.inventory_items_id_seq to anon, authenticated, service_role;
grant all on sequence public.product_inventory_links_id_seq to anon, authenticated, service_role;
grant all on sequence public.inventory_recipes_id_seq to anon, authenticated, service_role;
grant all on sequence public.inventory_recipe_components_id_seq to anon, authenticated, service_role;
grant all on sequence public.inventory_movements_id_seq to anon, authenticated, service_role;
