-- Block 13A: canonical inventory alert structure.
--
-- Inventory alerts are deliberately separate from order notifications and the
-- Master inbox. Policies describe which roles receive each alert category and
-- on which surface. Alert rows preserve one operational episode at a time.

set lock_timeout = '5s';
set statement_timeout = '60s';

create table public.inventory_alert_policies (
  id bigint generated by default as identity primary key,
  alert_category text not null,
  inventory_item_id bigint,
  is_enabled boolean not null default true,
  created_by_user_id uuid,
  updated_by_user_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_alert_policies_category_check
    check (alert_category in (
      'availability',
      'commitment',
      'production',
      'control',
      'procurement',
      'system'
    )),
  constraint inventory_alert_policies_inventory_item_id_fkey
    foreign key (inventory_item_id)
    references public.inventory_items(id)
    on delete cascade,
  constraint inventory_alert_policies_created_by_user_id_fkey
    foreign key (created_by_user_id)
    references public.profiles(id)
    on delete set null,
  constraint inventory_alert_policies_updated_by_user_id_fkey
    foreign key (updated_by_user_id)
    references public.profiles(id)
    on delete set null
);

create unique index inventory_alert_policies_global_category_uidx
  on public.inventory_alert_policies (alert_category)
  where inventory_item_id is null;

create unique index inventory_alert_policies_item_category_uidx
  on public.inventory_alert_policies (inventory_item_id, alert_category)
  where inventory_item_id is not null;

create index inventory_alert_policies_inventory_item_id_idx
  on public.inventory_alert_policies (inventory_item_id)
  where inventory_item_id is not null;

create index inventory_alert_policies_created_by_user_id_idx
  on public.inventory_alert_policies (created_by_user_id)
  where created_by_user_id is not null;

create index inventory_alert_policies_updated_by_user_id_idx
  on public.inventory_alert_policies (updated_by_user_id)
  where updated_by_user_id is not null;

create table public.inventory_alert_policy_routes (
  id bigint generated by default as identity primary key,
  inventory_alert_policy_id bigint not null,
  target_role public.user_role not null,
  surface text not null,
  created_at timestamptz not null default now(),
  constraint inventory_alert_policy_routes_policy_id_fkey
    foreign key (inventory_alert_policy_id)
    references public.inventory_alert_policies(id)
    on delete cascade,
  constraint inventory_alert_policy_routes_surface_check
    check (surface in (
      'inventory_center',
      'advisor_availability',
      'master_inventory',
      'kitchen_inventory',
      'counter_inventory',
      'admin_inventory'
    )),
  constraint inventory_alert_policy_routes_role_surface_check
    check (
      (surface = 'inventory_center' and target_role in ('admin', 'master'))
      or (surface = 'advisor_availability' and target_role = 'advisor')
      or (surface = 'master_inventory' and target_role = 'master')
      or (surface = 'kitchen_inventory' and target_role = 'kitchen')
      or (surface = 'counter_inventory' and target_role = 'counter')
      or (surface = 'admin_inventory' and target_role = 'admin')
    )
);

create unique index inventory_alert_policy_routes_route_uidx
  on public.inventory_alert_policy_routes (
    inventory_alert_policy_id,
    target_role,
    surface
  );

create index inventory_alert_policy_routes_role_surface_policy_idx
  on public.inventory_alert_policy_routes (
    target_role,
    surface,
    inventory_alert_policy_id
  );

create table public.inventory_alerts (
  id bigint generated by default as identity primary key,
  alert_key text not null,
  alert_category text not null,
  alert_type text not null,
  severity text not null,
  requires_action boolean not null default false,
  status text not null default 'open',
  inventory_item_id bigint,
  order_id bigint,
  planned_flow_id bigint,
  inventory_count_id bigint,
  order_timeline_event_id bigint,
  title text not null,
  message text,
  details jsonb not null default '{}'::jsonb,
  first_detected_at timestamptz not null default now(),
  last_detected_at timestamptz not null default now(),
  managed_by_user_id uuid,
  managed_at timestamptz,
  resolved_by_user_id uuid,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_alerts_key_not_blank_check
    check (btrim(alert_key) <> '' and char_length(alert_key) <= 240),
  constraint inventory_alerts_category_check
    check (alert_category in (
      'availability',
      'commitment',
      'production',
      'control',
      'procurement',
      'system'
    )),
  constraint inventory_alerts_type_not_blank_check
    check (btrim(alert_type) <> '' and char_length(alert_type) <= 120),
  constraint inventory_alerts_severity_check
    check (severity in ('info', 'warning', 'critical')),
  constraint inventory_alerts_status_check
    check (status in ('open', 'managed', 'resolved')),
  constraint inventory_alerts_title_not_blank_check
    check (btrim(title) <> '' and char_length(title) <= 240),
  constraint inventory_alerts_message_length_check
    check (message is null or char_length(message) <= 2000),
  constraint inventory_alerts_details_object_check
    check (jsonb_typeof(details) = 'object'),
  constraint inventory_alerts_detection_time_check
    check (last_detected_at >= first_detected_at),
  constraint inventory_alerts_management_audit_check
    check (
      (managed_at is null and managed_by_user_id is null)
      or (managed_at is not null and managed_by_user_id is not null)
    ),
  constraint inventory_alerts_resolution_audit_check
    check (
      (resolved_at is null and resolved_by_user_id is null)
      or resolved_at is not null
    ),
  constraint inventory_alerts_status_audit_check
    check (
      (status = 'open' and resolved_at is null and resolved_by_user_id is null)
      or (
        status = 'managed'
        and managed_at is not null
        and managed_by_user_id is not null
        and resolved_at is null
        and resolved_by_user_id is null
      )
      or (status = 'resolved' and resolved_at is not null)
    ),
  constraint inventory_alerts_inventory_item_id_fkey
    foreign key (inventory_item_id)
    references public.inventory_items(id)
    on delete set null,
  constraint inventory_alerts_order_id_fkey
    foreign key (order_id)
    references public.orders(id)
    on delete set null,
  constraint inventory_alerts_planned_flow_id_fkey
    foreign key (planned_flow_id)
    references public.inventory_planned_flows(id)
    on delete set null,
  constraint inventory_alerts_inventory_count_id_fkey
    foreign key (inventory_count_id)
    references public.inventory_counts(id)
    on delete set null,
  constraint inventory_alerts_order_timeline_event_id_fkey
    foreign key (order_timeline_event_id)
    references public.order_timeline_events(id)
    on delete set null,
  constraint inventory_alerts_managed_by_user_id_fkey
    foreign key (managed_by_user_id)
    references public.profiles(id)
    on delete set null,
  constraint inventory_alerts_resolved_by_user_id_fkey
    foreign key (resolved_by_user_id)
    references public.profiles(id)
    on delete set null
);

create unique index inventory_alerts_open_episode_uidx
  on public.inventory_alerts (alert_key)
  where status in ('open', 'managed');

create unique index inventory_alerts_timeline_event_uidx
  on public.inventory_alerts (order_timeline_event_id)
  where order_timeline_event_id is not null;

create index inventory_alerts_status_category_last_idx
  on public.inventory_alerts (status, alert_category, last_detected_at desc);

create index inventory_alerts_inventory_item_status_idx
  on public.inventory_alerts (inventory_item_id, status, last_detected_at desc)
  where inventory_item_id is not null;

create index inventory_alerts_order_id_idx
  on public.inventory_alerts (order_id)
  where order_id is not null;

create index inventory_alerts_planned_flow_id_idx
  on public.inventory_alerts (planned_flow_id)
  where planned_flow_id is not null;

create index inventory_alerts_inventory_count_id_idx
  on public.inventory_alerts (inventory_count_id)
  where inventory_count_id is not null;

create index inventory_alerts_managed_by_user_id_idx
  on public.inventory_alerts (managed_by_user_id)
  where managed_by_user_id is not null;

create index inventory_alerts_resolved_by_user_id_idx
  on public.inventory_alerts (resolved_by_user_id)
  where resolved_by_user_id is not null;

insert into public.inventory_alert_policies (
  alert_category,
  inventory_item_id,
  is_enabled
)
select category_name, null, true
from unnest(array[
  'availability',
  'commitment',
  'production',
  'control',
  'procurement',
  'system'
]::text[]) as category(category_name);

with default_routes(alert_category, target_role, surface) as (
  values
    ('availability', 'advisor'::public.user_role, 'advisor_availability'),
    ('availability', 'master'::public.user_role, 'inventory_center'),
    ('availability', 'master'::public.user_role, 'master_inventory'),
    ('availability', 'admin'::public.user_role, 'inventory_center'),
    ('availability', 'admin'::public.user_role, 'admin_inventory'),

    ('commitment', 'master'::public.user_role, 'inventory_center'),
    ('commitment', 'master'::public.user_role, 'master_inventory'),
    ('commitment', 'admin'::public.user_role, 'inventory_center'),
    ('commitment', 'admin'::public.user_role, 'admin_inventory'),

    ('production', 'kitchen'::public.user_role, 'kitchen_inventory'),
    ('production', 'master'::public.user_role, 'inventory_center'),
    ('production', 'master'::public.user_role, 'master_inventory'),
    ('production', 'admin'::public.user_role, 'inventory_center'),
    ('production', 'admin'::public.user_role, 'admin_inventory'),

    ('control', 'kitchen'::public.user_role, 'kitchen_inventory'),
    ('control', 'master'::public.user_role, 'inventory_center'),
    ('control', 'master'::public.user_role, 'master_inventory'),
    ('control', 'admin'::public.user_role, 'inventory_center'),
    ('control', 'admin'::public.user_role, 'admin_inventory'),

    ('procurement', 'master'::public.user_role, 'inventory_center'),
    ('procurement', 'master'::public.user_role, 'master_inventory'),
    ('procurement', 'admin'::public.user_role, 'inventory_center'),
    ('procurement', 'admin'::public.user_role, 'admin_inventory'),

    ('system', 'master'::public.user_role, 'inventory_center'),
    ('system', 'master'::public.user_role, 'master_inventory'),
    ('system', 'admin'::public.user_role, 'inventory_center'),
    ('system', 'admin'::public.user_role, 'admin_inventory')
)
insert into public.inventory_alert_policy_routes (
  inventory_alert_policy_id,
  target_role,
  surface
)
select policy.id, route.target_role, route.surface
from default_routes route
join public.inventory_alert_policies policy
  on policy.alert_category = route.alert_category
 and policy.inventory_item_id is null;

create or replace function public.inventory_alert_visible_to_current_user_v1(
  p_alert_id bigint
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_category text;
  v_inventory_item_id bigint;
  v_policy_id bigint;
  v_enabled boolean;
begin
  if v_actor is null or p_alert_id is null then
    return false;
  end if;

  if exists (
    select 1
    from public.user_roles actor_role
    where actor_role.user_id = v_actor
      and actor_role.role = 'admin'
  ) then
    return true;
  end if;

  -- Operational roles consume the surface-aware workspace RPC. Direct table
  -- reads are intentionally limited to the two roles that own this center.
  if not exists (
    select 1
    from public.user_roles actor_role
    where actor_role.user_id = v_actor
      and actor_role.role = 'master'
  ) then
    return false;
  end if;

  select alert.alert_category, alert.inventory_item_id
  into v_category, v_inventory_item_id
  from public.inventory_alerts alert
  where alert.id = p_alert_id;

  if not found then
    return false;
  end if;

  select policy.id, policy.is_enabled
  into v_policy_id, v_enabled
  from public.inventory_alert_policies policy
  where policy.alert_category = v_category
    and (
      policy.inventory_item_id = v_inventory_item_id
      or policy.inventory_item_id is null
    )
  order by (policy.inventory_item_id is not null) desc
  limit 1;

  if not found or not v_enabled then
    return false;
  end if;

  return exists (
    select 1
    from public.inventory_alert_policy_routes route
    where route.inventory_alert_policy_id = v_policy_id
      and route.target_role = 'master'
      and route.surface in ('inventory_center', 'master_inventory')
  );
end;
$$;

revoke all on function public.inventory_alert_visible_to_current_user_v1(bigint)
  from public, anon, authenticated;
grant execute on function public.inventory_alert_visible_to_current_user_v1(bigint)
  to service_role;

alter table public.inventory_alert_policies enable row level security;
alter table public.inventory_alert_policy_routes enable row level security;
alter table public.inventory_alerts enable row level security;

create policy inventory_alert_policies_select_admin
  on public.inventory_alert_policies
  for select
  to authenticated
  using ((select public.has_role('admin')));

create policy inventory_alert_policy_routes_select_admin
  on public.inventory_alert_policy_routes
  for select
  to authenticated
  using ((select public.has_role('admin')));

create policy inventory_alerts_select_authorized
  on public.inventory_alerts
  for select
  to authenticated
  using ((select public.inventory_alert_visible_to_current_user_v1(id)));

revoke all on table public.inventory_alert_policies
  from public, anon, authenticated;
revoke all on table public.inventory_alert_policy_routes
  from public, anon, authenticated;
revoke all on table public.inventory_alerts
  from public, anon, authenticated;

grant select, insert, update, delete on table public.inventory_alert_policies
  to service_role;
grant select, insert, update, delete on table public.inventory_alert_policy_routes
  to service_role;
grant select, insert, update, delete on table public.inventory_alerts
  to service_role;

revoke all on sequence public.inventory_alert_policies_id_seq
  from public, anon, authenticated;
revoke all on sequence public.inventory_alert_policy_routes_id_seq
  from public, anon, authenticated;
revoke all on sequence public.inventory_alerts_id_seq
  from public, anon, authenticated;
grant usage, select on sequence public.inventory_alert_policies_id_seq to service_role;
grant usage, select on sequence public.inventory_alert_policy_routes_id_seq to service_role;
grant usage, select on sequence public.inventory_alerts_id_seq to service_role;

comment on table public.inventory_alert_policies is
  'Configurable alert policy by category, optionally overriding one inventory item.';
comment on table public.inventory_alert_policy_routes is
  'Normalized role and application-surface routes for one inventory alert policy.';
comment on table public.inventory_alerts is
  'Canonical inventory alert episodes, independent from order notifications and inboxes.';
comment on function public.inventory_alert_visible_to_current_user_v1(bigint) is
  'RLS helper that resolves item overrides before category defaults and checks the caller roles.';
