-- Counter Block 7: atomic direct sale, governed discounts and exact price snapshots.
-- Canonical scope: /app/counter only. Reuses clients, orders, order_items,
-- order_timeline_events, kitchen status and the existing payment engine.

begin;

create table if not exists public.order_discount_rules (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  discount_pct numeric(9,4) not null,
  eligible_roles public.user_role[] not null default array[]::public.user_role[],
  payment_method_codes text[] not null default array[]::text[],
  payment_currencies public.currency_code[] not null default array[]::public.currency_code[],
  fulfillments public.fulfillment_type[] not null default array[]::public.fulfillment_type[],
  starts_at timestamptz,
  ends_at timestamptz,
  is_active boolean not null default false,
  created_by uuid references public.profiles(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint order_discount_rules_code_ck
    check (code = upper(code) and code ~ '^[A-Z0-9][A-Z0-9_-]{1,39}$'),
  constraint order_discount_rules_name_ck
    check (length(trim(name)) between 2 and 120),
  constraint order_discount_rules_pct_ck
    check (discount_pct > 0 and discount_pct <= 100),
  constraint order_discount_rules_roles_ck
    check (cardinality(eligible_roles) > 0),
  constraint order_discount_rules_window_ck
    check (ends_at is null or starts_at is null or ends_at > starts_at)
);

create index if not exists order_discount_rules_counter_active_idx
  on public.order_discount_rules (starts_at, ends_at, id)
  where is_active = true and 'counter'::public.user_role = any (eligible_roles);

alter table public.order_discount_rules enable row level security;
revoke all on table public.order_discount_rules from public, anon, authenticated;
grant all on table public.order_discount_rules to service_role;
grant usage, select on sequence public.order_discount_rules_id_seq to service_role;

comment on table public.order_discount_rules is
  'General, explicitly activated discount rules reusable by Counter and Advisor. Empty applicability arrays mean any value.';

create or replace function public.counter_normalize_phone(p_phone text)
returns text
language plpgsql
immutable
strict
set search_path = ''
as $function$
declare
  v_raw text := trim(p_phone);
  v_digits text;
  v_explicit boolean;
  v_result text;
begin
  v_explicit := v_raw ~ '^\s*(\+|00)';
  v_digits := regexp_replace(v_raw, '[^0-9]', '', 'g');

  if v_digits = '' then
    return null;
  end if;

  if v_explicit then
    if left(v_digits, 2) = '00' then
      v_digits := substring(v_digits from 3);
    end if;
    v_result := '+' || v_digits;
  elsif left(v_digits, 2) = '58' and length(v_digits) >= 11 then
    v_result := '+' || v_digits;
  elsif left(v_digits, 1) = '0' and length(v_digits) >= 10 then
    v_result := '+58' || substring(v_digits from 2);
  elsif length(v_digits) between 9 and 10 then
    v_result := '+58' || v_digits;
  else
    return null;
  end if;

  if v_result !~ '^\+[1-9][0-9]{6,14}$' then
    return null;
  end if;

  return v_result;
end;
$function$;

revoke all on function public.counter_normalize_phone(text) from public, anon;
grant execute on function public.counter_normalize_phone(text) to authenticated, service_role;

create unique index if not exists clients_normalized_phone_uk
  on public.clients (public.counter_normalize_phone(phone))
  where phone is not null
    and trim(phone) <> ''
    and public.counter_normalize_phone(phone) is not null;

alter table public.counter_command_receipts
  drop constraint if exists counter_command_receipts_type_ck;

alter table public.counter_command_receipts
  add constraint counter_command_receipts_type_ck
  check (
    command_type = any (
      array[
        'apply_order_payments',
        'record_manual_movement',
        'request_refund',
        'decide_authorization',
        'execute_refund',
        'dispatch_delivery',
        'record_delivery_return',
        'complete_delivery_digital_change',
        'close_money_account',
        'update_pickup_schedule',
        'change_pickup_items',
        'decide_pickup_change',
        'complete_pickup',
        'create_direct_sale'
      ]::text[]
    )
  );

create or replace function public.counter_direct_sale_item_notes(
  p_product_id bigint,
  p_qty numeric,
  p_item_note text,
  p_detail_lines jsonb
)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_product public.products%rowtype;
  v_component record;
  v_line text;
  v_alias text;
  v_component_id bigint;
  v_component_qty numeric;
  v_counted_units numeric := 0;
  v_detail text := nullif(trim(coalesce(p_item_note, '')), '');
  v_seen_component_ids bigint[] := array[]::bigint[];
  v_selected_component_ids bigint[] := array[]::bigint[];
  v_selected_component_qty numeric[] := array[]::numeric[];
  v_index integer;
begin
  select *
  into v_product
  from public.products
  where id = p_product_id
    and is_active = true;

  if not found then
    raise exception 'counter_product_unavailable';
  end if;

  if p_qty is null or p_qty <= 0 or p_qty > 999 then
    raise exception 'counter_item_quantity_invalid';
  end if;

  if length(coalesce(p_item_note, '')) > 500 then
    raise exception 'counter_item_note_too_long';
  end if;

  if p_detail_lines is null then
    p_detail_lines := '[]'::jsonb;
  end if;
  if jsonb_typeof(p_detail_lines) <> 'array' then
    raise exception 'counter_item_detail_invalid';
  end if;
  if jsonb_array_length(p_detail_lines) > 100 then
    raise exception 'counter_item_detail_too_long';
  end if;

  if v_product.is_detail_editable then
    if p_qty <> 1 then
      raise exception 'counter_configurable_product_quantity_must_be_one';
    end if;

    for v_line in
      select trim(value)
      from jsonb_array_elements_text(p_detail_lines)
    loop
      if v_line = '' then
        continue;
      end if;

      if v_line ~* '^para\s*:' then
        v_alias := nullif(trim(regexp_replace(v_line, '^para\s*:\s*', '', 'i')), '');
        if length(coalesce(v_alias, '')) > 120 then
          raise exception 'counter_item_alias_too_long';
        end if;
        continue;
      end if;

      if left(v_line, 5) <> '@sel|' then
        continue;
      end if;

      if v_line !~ '^@sel\|[0-9]+\|[0-9]+(\.[0-9]+)?$' then
        raise exception 'counter_item_selection_invalid';
      end if;

      v_component_id := split_part(v_line, '|', 2)::bigint;
      v_component_qty := split_part(v_line, '|', 3)::numeric;

      if v_component_qty <= 0
         or v_component_qty <> trunc(v_component_qty)
         or v_component_id = any(v_seen_component_ids) then
        raise exception 'counter_item_selection_invalid';
      end if;

      select
        pc.component_product_id,
        pc.component_mode,
        pc.quantity,
        pc.counts_toward_detail_limit,
        pc.is_required,
        pc.sort_order,
        component.name as component_name
      into v_component
      from public.product_components pc
      join public.products component
        on component.id = pc.component_product_id
       and component.is_active = true
      where pc.parent_product_id = p_product_id
        and pc.component_product_id = v_component_id;

      if not found then
        raise exception 'counter_item_component_unavailable';
      end if;

      if v_component.component_mode = 'fixed'
         and v_component_qty <> v_component.quantity then
        raise exception 'counter_item_fixed_component_quantity_invalid';
      end if;

      v_seen_component_ids := array_append(v_seen_component_ids, v_component_id);
      v_selected_component_ids := array_append(v_selected_component_ids, v_component_id);
      v_selected_component_qty := array_append(v_selected_component_qty, v_component_qty);

      if v_component.counts_toward_detail_limit then
        v_counted_units := v_counted_units + v_component_qty;
      end if;
    end loop;

    if exists (
      select 1
      from public.product_components pc
      where pc.parent_product_id = p_product_id
        and pc.component_mode = 'fixed'
        and pc.is_required = true
        and not (pc.component_product_id = any(v_seen_component_ids))
    ) then
      raise exception 'counter_item_required_component_missing';
    end if;

    if v_product.detail_units_limit > 0
       and v_counted_units <> v_product.detail_units_limit then
      raise exception 'counter_item_detail_limit_mismatch';
    end if;

    if v_alias is not null then
      v_detail := concat_ws(E'\n', v_detail, 'Para: ' || v_alias);
    end if;

    for v_component in
      select
        pc.component_product_id,
        pc.sort_order,
        component.name as component_name
      from public.product_components pc
      join public.products component
        on component.id = pc.component_product_id
      where pc.parent_product_id = p_product_id
        and pc.component_product_id = any(v_selected_component_ids)
      order by pc.sort_order, component.name, pc.id
    loop
      v_index := array_position(v_selected_component_ids, v_component.component_product_id);
      v_component_qty := v_selected_component_qty[v_index];
      v_detail := concat_ws(E'\n', v_detail, v_component_qty::text || ' ' || v_component.component_name);
      v_detail := concat_ws(
        E'\n',
        v_detail,
        '@sel|' || v_component.component_product_id::text || '|' || v_component_qty::text
      );
    end loop;
  else
    for v_component in
      select
        pc.quantity,
        pc.sort_order,
        component.name as component_name
      from public.product_components pc
      join public.products component
        on component.id = pc.component_product_id
       and component.is_active = true
      where pc.parent_product_id = p_product_id
        and pc.component_mode = 'fixed'
        and pc.is_required = true
      order by pc.sort_order, component.name, pc.id
    loop
      v_detail := concat_ws(
        E'\n',
        v_detail,
        (v_component.quantity * p_qty)::text || ' ' || v_component.component_name
      );
    end loop;
  end if;

  return nullif(v_detail, '');
end;
$function$;

revoke all on function public.counter_direct_sale_item_notes(bigint, numeric, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.counter_direct_sale_item_notes(bigint, numeric, text, jsonb)
  to service_role;

create or replace function public.trg_order_items_set_pricing()
returns trigger
language plpgsql
set search_path = ''
as $function$
declare
  v_product record;
  v_unit_price numeric;
  v_is_counter_direct_sale boolean := false;
  v_fx_rate numeric;
begin
  if new.override_unit_price_usd is not null
     or new.override_reason is not null
     or new.override_approved_by is not null
     or new.override_approved_at is not null then
    if not public.is_admin() then
      raise exception 'Only ADMIN can change item pricing or set an override.';
    end if;
  end if;

  select
    p.id,
    p.sku,
    p.name,
    p.base_price_usd,
    p.base_price_bs,
    p.source_price_currency,
    p.source_price_amount,
    coalesce(o.extra_fields #>> '{counter,quick_sale}', 'false') = 'true' as is_counter_direct_sale,
    case
      when coalesce(o.extra_fields #>> '{counter,quick_sale}', 'false') = 'true'
        then nullif(o.extra_fields #>> '{pricing,fx_rate}', '')::numeric
      else null
    end as fx_rate
  into v_product
  from public.products p
  join public.orders o on o.id = new.order_id
  where p.id = new.product_id;

  if not found then
    raise exception 'Invalid product_id';
  end if;

  v_is_counter_direct_sale := v_product.is_counter_direct_sale;
  v_fx_rate := v_product.fx_rate;

  if tg_op = 'INSERT' then
    new.sku_snapshot := v_product.sku;
    new.product_name_snapshot := v_product.name;

    if v_is_counter_direct_sale then
      if v_fx_rate is null or v_fx_rate <= 0 then
        raise exception 'counter_exchange_rate_invalid';
      end if;

      new.pricing_origin_currency := v_product.source_price_currency::text;
      new.pricing_origin_amount := v_product.source_price_amount;

      if v_product.source_price_currency::text = 'VES' then
        new.unit_price_bs_snapshot := round(v_product.source_price_amount, 2);
        new.line_total_bs_snapshot := round(v_product.source_price_amount * coalesce(new.qty, 0), 2);
        new.unit_price_usd_snapshot := round(v_product.source_price_amount / v_fx_rate, 2);
        new.line_total_usd := round(v_product.source_price_amount * coalesce(new.qty, 0) / v_fx_rate, 2);
      else
        new.unit_price_usd_snapshot := round(v_product.source_price_amount, 2);
        new.line_total_usd := round(v_product.source_price_amount * coalesce(new.qty, 0), 2);
        new.unit_price_bs_snapshot := round(v_product.source_price_amount * v_fx_rate, 2);
        new.line_total_bs_snapshot := round(v_product.source_price_amount * coalesce(new.qty, 0) * v_fx_rate, 2);
      end if;

      return new;
    end if;

    new.unit_price_usd_snapshot := v_product.base_price_usd;
  end if;

  v_unit_price := coalesce(new.override_unit_price_usd, new.unit_price_usd_snapshot);
  new.line_total_usd := coalesce(new.qty, 0) * coalesce(v_unit_price, 0);
  return new;
end;
$function$;

create or replace function public.counter_read_catalog()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $function$
declare
  v_payload jsonb;
begin
  if (select auth.uid()) is null
     or not (
       public.has_role('counter')
       or public.is_master_or_admin()
     ) then
    raise exception 'counter_access_denied' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'products',
      coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'id', p.id,
            'sku', p.sku,
            'name', coalesce(nullif(trim(p.name), ''), 'Producto'),
            'type', p.type::text,
            'sourcePriceCurrency', coalesce(p.source_price_currency::text, 'USD'),
            'sourcePriceAmount', coalesce(p.source_price_amount, 0),
            'basePriceUsd', coalesce(p.base_price_usd, 0),
            'basePriceBs', coalesce(p.base_price_bs, 0),
            'unitsPerService', coalesce(p.units_per_service, 0),
            'isDetailEditable', coalesce(p.is_detail_editable, false),
            'detailUnitsLimit', coalesce(p.detail_units_limit, 0),
            'isComboComponentSelectable', coalesce(p.is_combo_component_selectable, false)
          )
          order by p.name, p.id
        )
        from public.products p
        where p.is_active = true
      ), '[]'::jsonb),
    'components',
      coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'id', pc.id,
            'parentProductId', pc.parent_product_id,
            'componentProductId', pc.component_product_id,
            'componentMode', pc.component_mode::text,
            'quantity', coalesce(pc.quantity, 0),
            'countsTowardDetailLimit', coalesce(pc.counts_toward_detail_limit, false),
            'isRequired', coalesce(pc.is_required, false),
            'sortOrder', coalesce(pc.sort_order, 0),
            'notes', pc.notes,
            'parentSku', parent.sku,
            'parentName', parent.name,
            'componentSku', component.sku,
            'componentName', coalesce(nullif(trim(component.name), ''), 'Componente'),
            'componentType', component.type::text
          )
          order by pc.parent_product_id, pc.sort_order, pc.id
        )
        from public.product_components pc
        join public.products parent
          on parent.id = pc.parent_product_id
         and parent.is_active = true
        join public.products component
          on component.id = pc.component_product_id
         and component.is_active = true
      ), '[]'::jsonb),
    'discountRules',
      coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'id', rule.id,
            'code', rule.code,
            'name', rule.name,
            'description', rule.description,
            'discountPct', rule.discount_pct,
            'paymentMethodCodes', to_jsonb(rule.payment_method_codes),
            'paymentCurrencies', to_jsonb(rule.payment_currencies),
            'fulfillments', to_jsonb(rule.fulfillments),
            'startsAt', rule.starts_at,
            'endsAt', rule.ends_at
          )
          order by rule.discount_pct, rule.name, rule.id
        )
        from public.order_discount_rules rule
        where rule.is_active = true
          and 'counter'::public.user_role = any(rule.eligible_roles)
          and (rule.starts_at is null or rule.starts_at <= now())
          and (rule.ends_at is null or rule.ends_at > now())
      ), '[]'::jsonb)
  )
  into v_payload;

  return v_payload;
end;
$function$;

revoke all on function public.counter_read_catalog() from public, anon;
grant execute on function public.counter_read_catalog() to authenticated, service_role;

create or replace function public.counter_create_direct_sale(
  p_idempotency_key uuid,
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_uid uuid := (select auth.uid());
  v_receipt public.counter_command_receipts%rowtype;
  v_result jsonb;
  v_client public.clients%rowtype;
  v_client_id bigint;
  v_client_created boolean := false;
  v_client_name text;
  v_client_phone text;
  v_client_type text;
  v_fulfillment public.fulfillment_type;
  v_delivery_address text;
  v_delivery_gps_url text;
  v_receiver_name text;
  v_receiver_phone text;
  v_has_invoice boolean;
  v_has_delivery_note boolean;
  v_invoice_phone text;
  v_delivery_note_phone text;
  v_recent_addresses jsonb;
  v_schedule_asap boolean;
  v_schedule_date date;
  v_schedule_time time;
  v_schedule_at timestamptz;
  v_schedule_time_12 text;
  v_status public.order_status;
  v_now timestamptz := now();
  v_fx_rate numeric;
  v_payment_method text;
  v_payment_currency public.currency_code;
  v_payment_requires_change boolean;
  v_payment_change_for numeric;
  v_payment_change_currency public.currency_code;
  v_discount_rule public.order_discount_rules%rowtype;
  v_discount_rule_id bigint;
  v_discount_pct numeric := 0;
  v_invoice_tax_pct numeric := 0;
  v_order_id bigint;
  v_order_number text;
  v_order_extra jsonb;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty numeric;
  v_item_notes text;
  v_item_count integer;
  v_subtotal_usd numeric;
  v_subtotal_bs numeric;
  v_discount_usd numeric;
  v_discount_bs numeric;
  v_after_discount_usd numeric;
  v_after_discount_bs numeric;
  v_tax_usd numeric;
  v_tax_bs numeric;
  v_total_usd numeric;
  v_total_bs numeric;
  v_event_id bigint;
  v_actor_name text;
begin
  if v_uid is null
     or not (
       public.has_role('counter')
       or public.is_master_or_admin()
     ) then
    raise exception 'counter_access_denied' using errcode = '42501';
  end if;

  if p_idempotency_key is null then
    raise exception 'counter_idempotency_key_required';
  end if;
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'counter_direct_sale_payload_invalid';
  end if;

  insert into public.counter_command_receipts (
    idempotency_key,
    command_type,
    actor_user_id,
    request_payload
  )
  values (
    p_idempotency_key,
    'create_direct_sale',
    v_uid,
    p_payload
  )
  on conflict (actor_user_id, command_type, idempotency_key) do nothing
  returning * into v_receipt;

  if not found then
    select *
    into v_receipt
    from public.counter_command_receipts
    where actor_user_id = v_uid
      and command_type = 'create_direct_sale'
      and idempotency_key = p_idempotency_key
    for update;

    if v_receipt.request_payload is distinct from p_payload then
      raise exception 'counter_idempotency_key_reused';
    end if;
    if v_receipt.status <> 'completed' or v_receipt.result_payload is null then
      raise exception 'counter_idempotent_command_in_progress';
    end if;
    return v_receipt.result_payload;
  end if;

  v_client_name := nullif(trim(p_payload->>'clientName'), '');
  v_client_phone := public.counter_normalize_phone(p_payload->>'clientPhone');
  v_client_type := coalesce(nullif(trim(p_payload->>'clientType'), ''), 'own');

  if v_client_name is null or length(v_client_name) > 160 then
    raise exception 'counter_client_name_required';
  end if;
  if v_client_phone is null then
    raise exception 'counter_client_phone_invalid';
  end if;
  if v_client_type not in ('own', 'assigned', 'legacy') then
    raise exception 'counter_client_type_invalid';
  end if;

  if nullif(trim(p_payload->>'clientId'), '') is not null then
    v_client_id := (p_payload->>'clientId')::bigint;
    select *
    into v_client
    from public.clients
    where id = v_client_id
    for update;

    if not found then
      raise exception 'counter_client_not_found';
    end if;
    if not v_client.is_active then
      raise exception 'counter_client_inactive';
    end if;
    if public.counter_normalize_phone(v_client.phone) is not null
       and public.counter_normalize_phone(v_client.phone) <> v_client_phone then
      raise exception 'counter_client_phone_mismatch';
    end if;
    if public.counter_normalize_phone(v_client.phone) is null then
      update public.clients
      set phone = v_client_phone,
          updated_at = v_now
      where id = v_client_id
      returning * into v_client;
    end if;
  else
    select *
    into v_client
    from public.clients
    where public.counter_normalize_phone(phone) = v_client_phone
    order by is_active desc, id
    limit 1
    for update;

    if found then
      if not v_client.is_active then
        raise exception 'counter_client_inactive';
      end if;
      v_client_id := v_client.id;
    else
      begin
        insert into public.clients (
          full_name,
          phone,
          client_type
        )
        values (
          v_client_name,
          v_client_phone,
          v_client_type
        )
        returning * into v_client;
        v_client_id := v_client.id;
        v_client_created := true;
      exception
        when unique_violation then
          select *
          into v_client
          from public.clients
          where public.counter_normalize_phone(phone) = v_client_phone
          order by is_active desc, id
          limit 1
          for update;
          if not found or not v_client.is_active then
            raise exception 'counter_client_phone_conflict';
          end if;
          v_client_id := v_client.id;
      end;
    end if;
  end if;

  v_client_name := coalesce(nullif(trim(v_client.full_name), ''), v_client_name);
  v_client_phone := public.counter_normalize_phone(coalesce(v_client.phone, v_client_phone));

  v_fulfillment := case
    when p_payload->>'fulfillment' = 'delivery' then 'delivery'::public.fulfillment_type
    else 'pickup'::public.fulfillment_type
  end;
  v_delivery_address := nullif(trim(p_payload->>'deliveryAddress'), '');
  v_delivery_gps_url := nullif(trim(p_payload->>'deliveryGpsUrl'), '');
  v_receiver_name := nullif(trim(p_payload->>'receiverName'), '');
  v_receiver_phone := case
    when nullif(trim(p_payload->>'receiverPhone'), '') is null then null
    else public.counter_normalize_phone(p_payload->>'receiverPhone')
  end;

  if v_fulfillment = 'delivery' and v_delivery_address is null then
    raise exception 'counter_delivery_address_required';
  end if;
  if length(coalesce(v_delivery_address, '')) > 1000
     or length(coalesce(v_delivery_gps_url, '')) > 1000
     or length(coalesce(v_receiver_name, '')) > 160 then
    raise exception 'counter_delivery_data_too_long';
  end if;
  if nullif(trim(p_payload->>'receiverPhone'), '') is not null and v_receiver_phone is null then
    raise exception 'counter_receiver_phone_invalid';
  end if;

  v_has_invoice := coalesce((p_payload->>'hasInvoice')::boolean, false);
  v_has_delivery_note := coalesce((p_payload->>'hasDeliveryNote')::boolean, false);
  v_invoice_phone := case
    when nullif(trim(p_payload->>'invoicePhone'), '') is null then null
    else public.counter_normalize_phone(p_payload->>'invoicePhone')
  end;
  v_delivery_note_phone := case
    when nullif(trim(p_payload->>'deliveryNotePhone'), '') is null then null
    else public.counter_normalize_phone(p_payload->>'deliveryNotePhone')
  end;

  if nullif(trim(p_payload->>'invoicePhone'), '') is not null and v_invoice_phone is null then
    raise exception 'counter_invoice_phone_invalid';
  end if;
  if nullif(trim(p_payload->>'deliveryNotePhone'), '') is not null and v_delivery_note_phone is null then
    raise exception 'counter_delivery_note_phone_invalid';
  end if;

  v_recent_addresses := coalesce(v_client.recent_addresses, '[]'::jsonb);
  if v_fulfillment = 'delivery' then
    select coalesce(
      jsonb_agg(address_item order by sort_key),
      '[]'::jsonb
    )
    into v_recent_addresses
    from (
      select
        jsonb_build_object(
          'address', v_delivery_address,
          'gps_url', v_delivery_gps_url,
          'updated_at', v_now
        ) as address_item,
        0 as sort_key
      union all
      (
        select value, ordinality::integer
        from jsonb_array_elements(coalesce(v_client.recent_addresses, '[]'::jsonb))
          with ordinality
        where lower(trim(value->>'address')) <> lower(v_delivery_address)
        order by ordinality
        limit 4
      )
    ) recent;
  end if;

  update public.clients
  set
    recent_addresses = v_recent_addresses,
    billing_company_name = case when v_has_invoice then nullif(trim(p_payload->>'invoiceCompanyName'), '') else billing_company_name end,
    billing_tax_id = case when v_has_invoice then nullif(trim(p_payload->>'invoiceTaxId'), '') else billing_tax_id end,
    billing_address = case when v_has_invoice then nullif(trim(p_payload->>'invoiceAddress'), '') else billing_address end,
    billing_phone = case when v_has_invoice then v_invoice_phone else billing_phone end,
    delivery_note_name = case when v_has_delivery_note then nullif(trim(p_payload->>'deliveryNoteName'), '') else delivery_note_name end,
    delivery_note_document_id = case when v_has_delivery_note then nullif(trim(p_payload->>'deliveryNoteDocumentId'), '') else delivery_note_document_id end,
    delivery_note_address = case when v_has_delivery_note then nullif(trim(p_payload->>'deliveryNoteAddress'), '') else delivery_note_address end,
    delivery_note_phone = case when v_has_delivery_note then v_delivery_note_phone else delivery_note_phone end,
    updated_at = v_now
  where id = v_client_id
  returning * into v_client;

  select rate_bs_per_usd
  into v_fx_rate
  from public.exchange_rates
  where is_active = true
  order by effective_at desc, id desc
  limit 1;

  if v_fx_rate is null or v_fx_rate <= 0 then
    raise exception 'counter_exchange_rate_unavailable';
  end if;

  v_payment_method := lower(coalesce(nullif(trim(p_payload->>'paymentMethod'), ''), 'pos'));
  if v_payment_method not in (
    'pos',
    'payment_mobile',
    'transfer',
    'cash_usd',
    'cash_ves',
    'zelle',
    'mixed'
  ) then
    raise exception 'counter_payment_method_invalid';
  end if;

  v_payment_currency := case
    when p_payload->>'paymentCurrency' = 'USD' then 'USD'::public.currency_code
    else 'VES'::public.currency_code
  end;
  if v_payment_method in ('cash_usd', 'zelle') and v_payment_currency <> 'USD' then
    raise exception 'counter_payment_currency_invalid';
  end if;
  if v_payment_method in ('pos', 'payment_mobile', 'transfer', 'cash_ves')
     and v_payment_currency <> 'VES' then
    raise exception 'counter_payment_currency_invalid';
  end if;

  v_payment_requires_change := coalesce((p_payload->>'paymentRequiresChange')::boolean, false);
  v_payment_change_for := nullif(replace(trim(p_payload->>'paymentChangeFor'), ',', '.'), '')::numeric;
  v_payment_change_currency := case
    when p_payload->>'paymentChangeCurrency' = 'VES' then 'VES'::public.currency_code
    else 'USD'::public.currency_code
  end;
  if v_payment_requires_change and coalesce(v_payment_change_for, 0) <= 0 then
    raise exception 'counter_payment_change_amount_invalid';
  end if;

  v_discount_rule_id := nullif(trim(p_payload->>'discountRuleId'), '')::bigint;
  if v_discount_rule_id is not null then
    select *
    into v_discount_rule
    from public.order_discount_rules
    where id = v_discount_rule_id
    for share;

    if not found
       or not v_discount_rule.is_active
       or not ('counter'::public.user_role = any(v_discount_rule.eligible_roles))
       or (v_discount_rule.starts_at is not null and v_discount_rule.starts_at > v_now)
       or (v_discount_rule.ends_at is not null and v_discount_rule.ends_at <= v_now)
       or (
         cardinality(v_discount_rule.payment_method_codes) > 0
         and not (v_payment_method = any(v_discount_rule.payment_method_codes))
       )
       or (
         cardinality(v_discount_rule.payment_currencies) > 0
         and not (v_payment_currency = any(v_discount_rule.payment_currencies))
       )
       or (
         cardinality(v_discount_rule.fulfillments) > 0
         and not (v_fulfillment = any(v_discount_rule.fulfillments))
       ) then
      raise exception 'counter_discount_rule_not_applicable';
    end if;
    v_discount_pct := v_discount_rule.discount_pct;
  end if;

  if v_has_invoice then
    v_invoice_tax_pct := coalesce(
      nullif(replace(trim(p_payload->>'invoiceTaxPct'), ',', '.'), '')::numeric,
      16
    );
    if v_invoice_tax_pct < 0 or v_invoice_tax_pct > 100 then
      raise exception 'counter_invoice_tax_invalid';
    end if;
  end if;

  v_schedule_asap := coalesce((p_payload->>'scheduleAsap')::boolean, true);
  if v_schedule_asap then
    v_schedule_date := timezone('America/Caracas', v_now)::date;
    v_schedule_time := timezone('America/Caracas', v_now)::time(0);
    v_schedule_at := v_now;
    v_status := 'confirmed';
  else
    begin
      v_schedule_date := (p_payload->>'scheduledDate')::date;
      v_schedule_time := (p_payload->>'scheduledTime')::time;
    exception
      when others then
        raise exception 'counter_schedule_invalid';
    end;
    v_schedule_at := (v_schedule_date::text || ' ' || v_schedule_time::text)::timestamp
      at time zone 'America/Caracas';
    if v_schedule_at <= v_now then
      raise exception 'counter_schedule_must_be_future';
    end if;
    v_status := 'created';
  end if;

  v_schedule_time_12 := to_char(v_schedule_at at time zone 'America/Caracas', 'FMHH12:MI AM');

  if p_payload->'items' is null or jsonb_typeof(p_payload->'items') <> 'array' then
    raise exception 'counter_items_required';
  end if;
  v_item_count := jsonb_array_length(p_payload->'items');
  if v_item_count < 1 or v_item_count > 100 then
    raise exception 'counter_items_count_invalid';
  end if;

  select full_name
  into v_actor_name
  from public.profiles
  where id = v_uid;

  v_order_id := nextval('public.orders_id_seq'::regclass);
  v_order_number := 'VO-'
    || to_char(timezone('America/Caracas', v_now), 'YYYYMMDD')
    || '-'
    || lpad(
      v_order_id::text,
      greatest(4, length(v_order_id::text)),
      '0'
    );

  v_order_extra := jsonb_build_object(
    'schedule', jsonb_build_object(
      'date', v_schedule_date,
      'time_12', v_schedule_time_12,
      'time_24', to_char(v_schedule_time, 'HH24:MI'),
      'asap', v_schedule_asap
    ),
    'receiver', jsonb_build_object(
      'name', v_receiver_name,
      'phone', v_receiver_phone
    ),
    'delivery', jsonb_build_object(
      'address', case when v_fulfillment = 'delivery' then v_delivery_address else null end,
      'gps_url', case when v_fulfillment = 'delivery' then v_delivery_gps_url else null end
    ),
    'payment', jsonb_build_object(
      'method', v_payment_method,
      'currency', v_payment_currency,
      'requires_change', v_payment_requires_change,
      'change_for', case when v_payment_requires_change then v_payment_change_for else null end,
      'change_currency', v_payment_change_currency,
      'notes', nullif(trim(p_payload->>'paymentNote'), ''),
      'client_fund_used_usd', 0
    ),
    'documents', jsonb_build_object(
      'has_delivery_note', v_has_delivery_note,
      'has_invoice', v_has_invoice,
      'invoice_data_note', nullif(trim(p_payload->>'invoiceDataNote'), ''),
      'invoice_snapshot', case when v_has_invoice then jsonb_build_object(
        'company_name', v_client.billing_company_name,
        'tax_id', v_client.billing_tax_id,
        'address', v_client.billing_address,
        'phone', v_client.billing_phone
      ) else null end,
      'delivery_note_snapshot', case when v_has_delivery_note then jsonb_build_object(
        'name', v_client.delivery_note_name,
        'document_id', v_client.delivery_note_document_id,
        'address', v_client.delivery_note_address,
        'phone', v_client.delivery_note_phone
      ) else null end
    ),
    'pricing', jsonb_build_object(
      'fx_rate', v_fx_rate,
      'discount_enabled', v_discount_rule_id is not null,
      'discount_rule_id', v_discount_rule_id,
      'discount_rule_code', case when v_discount_rule_id is not null then v_discount_rule.code else null end,
      'discount_rule_name', case when v_discount_rule_id is not null then v_discount_rule.name else null end,
      'discount_pct', v_discount_pct,
      'invoice_tax_pct', v_invoice_tax_pct
    ),
    'note', nullif(trim(p_payload->>'note'), ''),
    'ui', jsonb_build_object('quote_only', false),
    'counter', jsonb_build_object(
      'quick_sale', true,
      'created_at', v_now,
      'scheduled_by_counter', not v_schedule_asap,
      'client_name_snapshot', v_client_name,
      'client_phone_snapshot', v_client_phone,
      'operator_user_id', v_uid,
      'operator_name_snapshot', coalesce(nullif(trim(v_actor_name), ''), 'Mostrador'),
      'attribution', 'counter'
    )
  );

  insert into public.orders (
    id,
    order_number,
    client_id,
    created_by_user_id,
    attributed_advisor_id,
    source,
    fulfillment,
    status,
    sent_to_kitchen_at,
    sent_to_kitchen_by,
    total_usd,
    total_bs_snapshot,
    is_price_locked,
    delivery_address,
    receiver_name,
    receiver_phone,
    notes,
    extra_fields
  )
  values (
    v_order_id,
    v_order_number,
    v_client_id,
    v_uid,
    null,
    'walk_in',
    v_fulfillment,
    v_status,
    case when v_schedule_asap then v_now else null end,
    case when v_schedule_asap then v_uid else null end,
    0,
    0,
    false,
    case when v_fulfillment = 'delivery' then v_delivery_address else null end,
    v_receiver_name,
    v_receiver_phone,
    nullif(trim(p_payload->>'note'), ''),
    v_order_extra
  );

  for v_item in
    select value
    from jsonb_array_elements(p_payload->'items')
  loop
    begin
      v_qty := (v_item->>'qty')::numeric;
      select *
      into v_product
      from public.products
      where id = (v_item->>'productId')::bigint
        and is_active = true;
    exception
      when others then
        raise exception 'counter_item_invalid';
    end;

    if not found then
      raise exception 'counter_product_unavailable';
    end if;
    if v_qty is null or v_qty <= 0 or v_qty > 999 then
      raise exception 'counter_item_quantity_invalid';
    end if;

    v_item_notes := public.counter_direct_sale_item_notes(
      v_product.id,
      v_qty,
      v_item->>'notes',
      coalesce(v_item->'editableDetailLines', '[]'::jsonb)
    );

    insert into public.order_items (
      order_id,
      product_id,
      qty,
      unit_price_usd_snapshot,
      line_total_usd,
      product_name_snapshot,
      sku_snapshot,
      notes,
      unit_price_bs_snapshot,
      line_total_bs_snapshot,
      pricing_origin_currency,
      pricing_origin_amount
    )
    values (
      v_order_id,
      v_product.id,
      v_qty,
      0,
      0,
      v_product.name,
      v_product.sku,
      v_item_notes,
      0,
      0,
      v_product.source_price_currency::text,
      v_product.source_price_amount
    );
  end loop;

  select
    round(coalesce(sum(line_total_usd), 0), 2),
    round(coalesce(sum(line_total_bs_snapshot), 0), 2)
  into v_subtotal_usd, v_subtotal_bs
  from public.order_items
  where order_id = v_order_id;

  v_discount_usd := round(v_subtotal_usd * v_discount_pct / 100, 2);
  v_discount_bs := round(v_subtotal_bs * v_discount_pct / 100, 2);
  v_after_discount_usd := round(v_subtotal_usd - v_discount_usd, 2);
  v_after_discount_bs := round(v_subtotal_bs - v_discount_bs, 2);
  v_tax_usd := round(v_after_discount_usd * v_invoice_tax_pct / 100, 2);
  v_tax_bs := round(v_after_discount_bs * v_invoice_tax_pct / 100, 2);
  v_total_usd := round(v_after_discount_usd + v_tax_usd, 2);
  v_total_bs := round(v_after_discount_bs + v_tax_bs, 2);

  v_order_extra := jsonb_set(
    v_order_extra,
    '{pricing}',
    (v_order_extra->'pricing') || jsonb_build_object(
      'subtotal_before_discount_usd', v_subtotal_usd,
      'subtotal_before_discount_bs', v_subtotal_bs,
      'discount_amount_usd', v_discount_usd,
      'discount_amount_bs', v_discount_bs,
      'subtotal_usd', v_after_discount_usd,
      'subtotal_bs', v_after_discount_bs,
      'subtotal_after_discount_usd', v_after_discount_usd,
      'subtotal_after_discount_bs', v_after_discount_bs,
      'invoice_tax_amount_usd', v_tax_usd,
      'invoice_tax_amount_bs', v_tax_bs,
      'total_usd', v_total_usd,
      'total_bs', v_total_bs
    ),
    true
  );

  update public.orders
  set
    total_usd = v_total_usd,
    total_bs_snapshot = v_total_bs,
    extra_fields = v_order_extra
  where id = v_order_id;

  insert into public.order_timeline_events (
    order_id,
    order_number,
    event_type,
    event_group,
    title,
    message,
    severity,
    actor_user_id,
    payload
  )
  values (
    v_order_id,
    v_order_number,
    case when v_schedule_asap then 'counter_quick_sale_created' else 'counter_scheduled_order_created' end,
    case when v_schedule_asap then 'kitchen' else 'approval' end,
    case when v_schedule_asap then 'Venta de mostrador enviada a cocina' else 'Pedido agendado por mostrador' end,
    case
      when v_schedule_asap then 'Mostrador creo la venta y la envio directamente a cocina.'
      else 'Mostrador creo un pedido futuro para que Master lo envie a cocina cuando corresponda.'
    end,
    case when v_schedule_asap then 'info' else 'warning' end,
    v_uid,
    jsonb_build_object(
      'source', 'counter_direct_sale',
      'fulfillment', v_fulfillment,
      'scheduled', not v_schedule_asap,
      'schedule_date', v_schedule_date,
      'schedule_time', to_char(v_schedule_time, 'HH24:MI'),
      'client_id', v_client_id,
      'client_created', v_client_created,
      'discount_rule_id', v_discount_rule_id
    )
  )
  returning id into v_event_id;

  insert into public.order_timeline_event_recipients (
    event_id,
    target_role,
    requires_action
  )
  values (
    v_event_id,
    case when v_schedule_asap then 'kitchen' else 'master' end,
    true
  );

  v_result := jsonb_build_object(
    'id', v_order_id,
    'orderNumber', v_order_number,
    'sentToKitchen', v_schedule_asap,
    'scheduled', not v_schedule_asap,
    'clientId', v_client_id,
    'clientCreated', v_client_created,
    'fxRate', v_fx_rate,
    'subtotalUsd', v_subtotal_usd,
    'subtotalBs', v_subtotal_bs,
    'totalUsd', v_total_usd,
    'totalBs', v_total_bs,
    'discountRuleId', v_discount_rule_id,
    'discountPct', v_discount_pct
  );

  update public.counter_command_receipts
  set
    order_id = v_order_id,
    status = 'completed',
    result_payload = v_result,
    completed_at = v_now
  where id = v_receipt.id
    and actor_user_id = v_uid
    and status = 'started';

  if not found then
    raise exception 'counter_direct_sale_receipt_completion_failed';
  end if;

  return v_result;
end;
$function$;

revoke all on function public.counter_create_direct_sale(uuid, jsonb)
  from public, anon;
grant execute on function public.counter_create_direct_sale(uuid, jsonb)
  to authenticated, service_role;

commit;
