// Isolated Postgres (PGlite); no production connection or credentials.
// Install the pinned test-only runtime outside package.json:
// npm install --prefix outputs/crm-auto-link-test-runtime --no-save --ignore-scripts --package-lock=false @electric-sql/pglite@0.5.8
import { PGlite } from '../../outputs/crm-auto-link-test-runtime/node_modules/@electric-sql/pglite/dist/index.js';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const read = (name) => readFileSync(new URL(`../../supabase/migrations/${name}`, import.meta.url), 'utf8');
const db = new PGlite();
await db.exec(`
create role anon; create role authenticated; create role service_role;
create schema auth; create schema app_private;
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
create function auth.role() returns text language sql as $$ select coalesce(nullif(current_setting('test.role',true),''),'authenticated') $$;
create function auth.jwt() returns jsonb language sql as $$ select jsonb_build_object('role',auth.role()) $$;
create function public.has_role(text) returns boolean language sql as $$ select auth.uid() is not null and ($1='advisor' or auth.role()='admin') $$;
create function public.is_master_or_admin() returns boolean language sql as $$ select auth.role()='admin' $$;
create table profiles(id uuid primary key);
create table products(id bigint primary key,sku text,name text,type text,is_active boolean default true,extra_fields jsonb default '{}',base_price_usd numeric default 0,source_price_amount numeric default 0);
create table crm_plays(id bigint primary key,name text,status text,starts_at timestamptz,ends_at timestamptz,benefit_selection_mode text default 'single',purchase_requirement_mode text default 'none',minimum_order_amount_usd numeric);
create table crm_play_members(id bigint primary key,play_id bigint,client_id bigint,advisor_id_snapshot uuid,workflow_status text default 'pending',benefit_status text default 'available',benefit_reserved_at timestamptz,benefit_redeemed_at timestamptz,benefit_expired_at timestamptz,selected_play_benefit_id bigint,selected_benefit_at timestamptz,selected_benefit_by_user_id uuid);
create table crm_play_benefits(id bigint primary key,play_id bigint,product_id bigint,quantity numeric default 1,sort_order int default 1,unit_benefit_value_usd numeric default 4,unit_advisor_cost_usd numeric default 1.5,unit_company_cost_usd numeric default 2.5);
create table crm_play_benefit_upgrades(id bigint primary key,play_id bigint,play_benefit_id bigint,target_product_id bigint,target_quantity numeric,customer_difference_usd_snapshot numeric);
create table crm_play_member_benefit_selections(play_member_id bigint,play_benefit_id bigint,play_id bigint,selected_by_user_id uuid,selected_at timestamptz,primary key(play_member_id,play_benefit_id));
create table orders(id bigint primary key,order_number text,client_id bigint,attributed_advisor_id uuid,status text default 'created',extra_fields jsonb default '{"pricing":{"fx_rate":100}}',source text default 'advisor',last_modified_by uuid);
create table order_items(id bigint generated by default as identity primary key,order_id bigint,product_id bigint,qty numeric default 1,crm_play_member_id bigint,crm_play_benefit_id bigint,crm_play_benefit_upgrade_id bigint,admin_price_override_usd numeric,override_unit_price_usd numeric,pricing_origin_currency text,pricing_origin_amount numeric,unit_price_usd_snapshot numeric default 0,line_total_usd numeric default 0,unit_price_bs_snapshot numeric default 0,line_total_bs_snapshot numeric default 0,sku_snapshot text,product_name_snapshot text,notes text);
create table crm_play_redemptions(id bigint generated always as identity primary key,play_member_id bigint,play_benefit_id bigint,play_benefit_upgrade_id bigint,order_id bigint,order_item_id bigint,product_id bigint,quantity numeric,status text,reserved_by_user_id uuid,reserved_at timestamptz,redeemed_by_user_id uuid,redeemed_at timestamptz,voided_at timestamptz,void_reason text,created_at timestamptz default now(),play_name_snapshot text,unit_benefit_value_usd numeric,unit_advisor_cost_usd numeric,unit_company_cost_usd numeric,benefit_value_usd numeric,benefit_credit_usd numeric,customer_paid_difference_usd numeric,advisor_charge_usd numeric,company_cost_usd numeric);
create unique index active_benefit on crm_play_redemptions(play_member_id,play_benefit_id) where status in ('reserved','redeemed');
create table crm_play_member_events(id bigint generated always as identity,play_member_id bigint,event_type text,from_status text,to_status text,note text,actor_user_id uuid,created_at timestamptz default now());
insert into profiles values('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002');
select set_config('test.uid','00000000-0000-0000-0000-000000000001',false);
insert into products values(1,'SINGLE_6','Normal pack','combo',true,'{}',4,4),(2,'ANIVERSARIO_SINGLEPACK','Legacy anniversary','gambit',true,'{"catalog_access_scope":"advisor_gift"}',0,0),(3,'DONDY','Discretionary only','gambit',true,'{"catalog_access_scope":"advisor_gift_only"}',0,0);
insert into crm_plays(id,name,status,starts_at,ends_at) values(1,'Aniversario · septiembre de 2026','active',now()-interval '1 day',now()+interval '1 day');
insert into crm_play_benefits(id,play_id,product_id) values(1,1,1);
insert into crm_play_members(id,play_id,client_id,advisor_id_snapshot) values(1,1,1,auth.uid());
insert into orders(id,order_number,client_id,attributed_advisor_id) values(1,'test-1',1,auth.uid()),(2,'test-2',2,auth.uid()),(3,'test-3',1,auth.uid());
`);
function extract(file, name) {
  const source = read(file);
  const start = source.toLowerCase().indexOf(`create or replace function ${name}(`);
  assert.ok(start >= 0, name);
  const opener = /as\s+(\$[a-z_]*\$)/i.exec(source.slice(start));
  assert.ok(opener, name);
  const bodyStart = start + opener.index + opener[0].length;
  const end = source.indexOf(opener[1], bodyStart);
  assert.ok(end > start, name);
  return source.slice(start, end + opener[1].length) + ';';
}
const lifecycle = '20260912001929_crm_benefit_reservation_delivery_lifecycle_v1.sql';
await db.exec(extract('20260827193000_crm_play_economics_combinations_v3.sql', 'public.crm_set_play_benefits_v2'));
await db.exec(extract('20260918124833_gambit_application_modes.sql', 'app_private.crm_order_item_guard_v1'));
for (const name of ['crm_play_redemption_guard_v1','crm_reserve_order_item_benefit_v1','crm_release_order_item_reservation_v1','crm_finalize_order_benefits_on_delivery_v1','crm_void_play_redemptions_on_order_cancel_v1']) {
  await db.exec(extract(lifecycle, `app_private.${name}`));
}
await db.exec(`
create trigger crm_order_items_guard before insert or update on order_items for each row execute function app_private.crm_order_item_guard_v1();
create trigger reserve after insert on order_items for each row when(new.crm_play_member_id is not null) execute function app_private.crm_reserve_order_item_benefit_v1();
create trigger release before delete on order_items for each row when(old.crm_play_member_id is not null) execute function app_private.crm_release_order_item_reservation_v1();
create trigger redemption_guard before insert or update or delete on crm_play_redemptions for each row execute function app_private.crm_play_redemption_guard_v1();
create trigger finalize after update of status on orders for each row execute function app_private.crm_finalize_order_benefits_on_delivery_v1();
create trigger cancel after update of status on orders for each row execute function app_private.crm_void_play_redemptions_on_order_cancel_v1();
`);
await db.exec(read('20260918171721_crm_catalog_gift_auto_link.sql'));
const rows = async (sql) => (await db.query(sql)).rows;
let passed = 0;
async function check(name, fn) { await fn(); passed++; console.log(`PASS ${name}`); }
await check('explicit alias resolves one eligible campaign', async () => {
  const [row] = await rows(`select public.crm_resolve_catalog_gift_v1(1,2) matches`);
  assert.equal(row.matches.length,1); assert.equal(row.matches[0].target_product_id,1);
});
await check('normal paid product and discretionary-only do not auto-link', async () => {
  for (const id of [1,3]) assert.deepEqual((await rows(`select public.crm_resolve_catalog_gift_v1(1,${id}) matches`))[0].matches,[]);
});
await check('other advisor cannot see this membership', async () => {
  await db.exec(`select set_config('test.uid','00000000-0000-0000-0000-000000000002',false)`);
  assert.deepEqual((await rows(`select public.crm_resolve_catalog_gift_v1(1,2) matches`))[0].matches,[]);
  await assert.rejects(db.exec(`insert into order_items(order_id,product_id) values(1,2)`), /asesor/);
  await db.exec(`select set_config('test.uid','00000000-0000-0000-0000-000000000001',false)`);
});
await check('no membership preserves ordinary discretionary item', async () => {
  await db.exec(`insert into order_items(order_id,product_id) values(2,2)`);
  assert.equal((await rows(`select crm_play_member_id from order_items where order_id=2`))[0].crm_play_member_id,null);
});
await check('quantity mismatch fails without a reservation', async () => {
  await assert.rejects(db.exec(`insert into order_items(order_id,product_id,qty) values(1,2,2)`), /cantidad/);
  assert.equal((await rows(`select count(*) n from crm_play_redemptions`))[0].n,0);
});
await check('catalog insert normalizes one line and reserves exactly once preserving notes', async () => {
  await db.exec(`insert into order_items(order_id,product_id,notes) values(1,2,E'2 Tequeños\n@sel|5|2')`);
  const [item]=await rows(`select * from order_items where order_id=1`);
  assert.equal(item.product_id,1); assert.equal(item.crm_play_member_id,1); assert.equal(Number(item.line_total_usd),0); assert.match(item.notes,/@sel\|5\|2/);
  const [r]=await rows(`select * from crm_play_redemptions`);
  assert.equal(r.status,'reserved'); assert.equal(r.redeemed_at,null); assert.equal(Number(r.advisor_charge_usd),1.5);
});
await check('repeat click/order cannot turn the same entitlement into a free discretionary gift', async () => {
  await assert.rejects(db.exec(`insert into order_items(order_id,product_id) values(3,2)`), /reservado/);
});
await check('removing gift releases reservation; adding again creates one active reservation', async () => {
  await db.exec(`delete from order_items where order_id=1`);
  assert.equal((await rows(`select benefit_status from crm_play_members where id=1`))[0].benefit_status,'available');
  await db.exec(`insert into order_items(order_id,product_id) values(1,2)`);
  assert.equal((await rows(`select count(*) n from crm_play_redemptions where status='reserved'`))[0].n,1);
});
await check('only delivery applies gift; cancellation releases it', async () => {
  await db.exec(`update orders set status='delivered' where id=1`);
  assert.equal((await rows(`select benefit_status from crm_play_members where id=1`))[0].benefit_status,'redeemed');
  await assert.rejects(db.exec(`insert into order_items(order_id,product_id) values(3,2)`), /aplicado/);
  await db.exec(`update orders set status='cancelled' where id=1`);
  assert.equal((await rows(`select benefit_status from crm_play_members where id=1`))[0].benefit_status,'available');
});
await check('conditional campaigns cannot silently exonerate an unprepared free item', async () => {
  await db.exec(`update crm_plays set purchase_requirement_mode='minimum_order',minimum_order_amount_usd=10 where id=1`);
  await assert.rejects(db.exec(`insert into order_items(order_id,product_id) values(3,2)`), /condiciones/);
  await db.exec(`update crm_plays set purchase_requirement_mode='none' where id=1`);
});
await check('ambiguity never chooses first campaign', async () => {
  await db.exec(`insert into crm_plays(id,name,status) values(2,'Another','active'); insert into crm_play_benefits(id,play_id,product_id) values(2,2,1); insert into crm_play_members(id,play_id,client_id,advisor_id_snapshot) values(2,2,1,auth.uid()); insert into crm_play_catalog_aliases(play_benefit_id,source_product_id) values(2,2);`);
  await assert.rejects(db.exec(`insert into order_items(order_id,product_id) values(3,2)`), /varias jugadas/);
});
await check('paused/expired plays are not automatic candidates', async () => {
  await db.exec(`update crm_plays set status='paused' where id=1; update crm_plays set ends_at=now()-interval '1 second' where id=2;`);
  assert.deepEqual((await rows(`select public.crm_resolve_catalog_gift_v1(1,2) matches`))[0].matches,[]);
});
await check('unauthenticated lookup denied and alias table not writable by authenticated', async () => {
  await db.exec(`select set_config('test.uid','',false)`);
  await assert.rejects(db.exec(`select public.crm_resolve_catalog_gift_v1(1,2)`), /Solo el asesor/);
  assert.equal((await rows(`select has_table_privilege('authenticated','crm_play_catalog_aliases','INSERT') allowed`))[0].allowed,false);
});
console.log(`${passed} database integration checks passed in isolated Postgres`);
await db.close();
